// Generated by ProtoGen, Version=2.3.0.277, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!

using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Linq;
using System.Runtime.CompilerServices;
using scg = System.Collections.Generic;

namespace PhoneNumbers
{
    #region Messages

    [DebuggerNonUserCode]
    [CompilerGenerated]
    [GeneratedCode("ProtoGen", "2.3.0.277")]
    public class PhoneMetadata
    {
        public const int GeneralDescFieldNumber = 1;

        public const int FixedLineFieldNumber = 2;

        public const int MobileFieldNumber = 3;

        public const int TollFreeFieldNumber = 4;

        public const int PremiumRateFieldNumber = 5;

        public const int SharedCostFieldNumber = 6;

        public const int PersonalNumberFieldNumber = 7;

        public const int VoipFieldNumber = 8;

        public const int PagerFieldNumber = 21;

        public const int UanFieldNumber = 25;

        public const int EmergencyFieldNumber = 27;

        public const int VoicemailFieldNumber = 28;

        public const int ShortCodeFieldNumber = 29;

        public const int StandardRateFieldNumber = 30;

        public const int CarrierSpecificFieldNumber = 31;

        public const int SmsServicesFieldNumber = 33;

        public const int NoInternationalDiallingFieldNumber = 24;

        public const int IdFieldNumber = 9;

        public const int CountryCodeFieldNumber = 10;

        public const int InternationalPrefixFieldNumber = 11;

        public const int PreferredInternationalPrefixFieldNumber = 17;

        public const int NationalPrefixFieldNumber = 12;

        public const int PreferredExtnPrefixFieldNumber = 13;

        public const int NationalPrefixForParsingFieldNumber = 15;

        public const int NationalPrefixTransformRuleFieldNumber = 16;

        public const int SameMobileAndFixedLinePatternFieldNumber = 18;

        public const int NumberFormatFieldNumber = 19;

        public const int IntlNumberFormatFieldNumber = 20;

        public const int MainCountryForCodeFieldNumber = 22;

        public const int LeadingDigitsFieldNumber = 23;

        public const int LeadingZeroPossibleFieldNumber = 26;

        public const int MobileNumberPortableRegionFieldNumber = 32;
        private readonly scg.List<NumberFormat> intlNumberFormat_ = new scg.List<NumberFormat>();
        private readonly scg.List<NumberFormat> numberFormat_ = new scg.List<NumberFormat>();

        public static PhoneMetadata DefaultInstance { get; } = new Builder().BuildPartial();

        public PhoneMetadata DefaultInstanceForType => DefaultInstance;

        protected PhoneMetadata ThisMessage => this;

        public bool HasGeneralDesc { get; private set; }
        public PhoneNumberDesc GeneralDesc { get; private set; } = PhoneNumberDesc.DefaultInstance;

        public bool HasFixedLine { get; private set; }
        public PhoneNumberDesc FixedLine { get; private set; } = PhoneNumberDesc.DefaultInstance;
        public bool HasMobile { get; private set; }

        public PhoneNumberDesc Mobile { get; private set; } = PhoneNumberDesc.DefaultInstance;
        public bool HasTollFree { get; private set; }

        public PhoneNumberDesc TollFree { get; private set; } = PhoneNumberDesc.DefaultInstance;

        public bool HasPremiumRate { get; private set; }
        public PhoneNumberDesc PremiumRate { get; private set; } = PhoneNumberDesc.DefaultInstance;

        public bool HasSharedCost { get; private set; }
        public PhoneNumberDesc SharedCost { get; private set; } = PhoneNumberDesc.DefaultInstance;

        public bool HasPersonalNumber { get; private set; }
        public PhoneNumberDesc PersonalNumber { get; private set; } = PhoneNumberDesc.DefaultInstance;
        public bool HasVoip { get; private set; }

        public PhoneNumberDesc Voip { get; private set; } = PhoneNumberDesc.DefaultInstance;
        public bool HasPager { get; private set; }

        public PhoneNumberDesc Pager { get; private set; } = PhoneNumberDesc.DefaultInstance;
        public bool HasUan { get; private set; }

        public PhoneNumberDesc Uan { get; private set; } = PhoneNumberDesc.DefaultInstance;
        public bool HasEmergency { get; private set; }

        public PhoneNumberDesc Emergency { get; private set; } = PhoneNumberDesc.DefaultInstance;
        public bool HasVoicemail { get; private set; }

        public PhoneNumberDesc Voicemail { get; private set; } = PhoneNumberDesc.DefaultInstance;
        public bool HasShortCode { get; private set; }

        public PhoneNumberDesc ShortCode { get; private set; } = PhoneNumberDesc.DefaultInstance;
        public bool HasStandardRate { get; private set; }

        public PhoneNumberDesc StandardRate { get; private set; } = PhoneNumberDesc.DefaultInstance;

        public bool HasCarrierSpecific { get; private set; }
        public PhoneNumberDesc CarrierSpecific { get; private set; } = PhoneNumberDesc.DefaultInstance;
        public bool HasSmsServices { get; private set; }

        public PhoneNumberDesc SmsServices { get; private set; } = PhoneNumberDesc.DefaultInstance;
        public bool HasNoInternationalDialling { get; private set; }

        public PhoneNumberDesc NoInternationalDialling { get; private set; } = PhoneNumberDesc.DefaultInstance;
        public bool HasId { get; private set; }

        public string Id { get; private set; } = "";
        public bool HasCountryCode { get; private set; }

        public int CountryCode { get; private set; }
        public bool HasInternationalPrefix { get; private set; }

        public string InternationalPrefix { get; private set; } = "";
        public bool HasPreferredInternationalPrefix { get; private set; }

        public string PreferredInternationalPrefix { get; private set; } = "";
        public bool HasNationalPrefix { get; private set; }

        public string NationalPrefix { get; private set; } = "";
        public bool HasPreferredExtnPrefix { get; private set; }

        public string PreferredExtnPrefix { get; private set; } = "";
        public bool HasNationalPrefixForParsing { get; private set; }

        public string NationalPrefixForParsing { get; private set; } = "";
        public bool HasNationalPrefixTransformRule { get; private set; }

        public string NationalPrefixTransformRule { get; private set; } = "";
        public bool HasSameMobileAndFixedLinePattern { get; private set; }

        public bool SameMobileAndFixedLinePattern { get; private set; }

        public scg.IList<NumberFormat> NumberFormatList => numberFormat_;

        public int NumberFormatCount => numberFormat_.Count;

        public scg.IList<NumberFormat> IntlNumberFormatList => intlNumberFormat_;

        public int IntlNumberFormatCount => intlNumberFormat_.Count;

        public bool HasMainCountryForCode { get; private set; }

        public bool MainCountryForCode { get; private set; }

        public bool HasLeadingDigits { get; private set; }

        public string LeadingDigits { get; private set; } = "";

        public bool HasLeadingZeroPossible { get; private set; }

        public bool LeadingZeroPossible { get; private set; }

        public bool HasMobileNumberPortableRegion { get; private set; }

        public bool MobileNumberPortableRegion { get; private set; }

        public bool IsInitialized
        {
            get
            {
                if (!HasId) return false;
                return NumberFormatList.All(element => element.IsInitialized) && IntlNumberFormatList.All(element => element.IsInitialized);
            }
        }

        public NumberFormat GetNumberFormat(int index) => numberFormat_[index];

        public NumberFormat GetIntlNumberFormat(int index) => intlNumberFormat_[index];

        public static Builder CreateBuilder() => new Builder();

        public Builder ToBuilder() => CreateBuilder(this);

        public Builder CreateBuilderForType() => new Builder();

        public static Builder CreateBuilder(PhoneMetadata prototype) => new Builder().MergeFrom(prototype);

        [DebuggerNonUserCode]
        [CompilerGenerated]
        [GeneratedCode("ProtoGen", "2.3.0.277")]
        public class Builder
        {
            protected Builder ThisBuilder => this;

            protected PhoneMetadata MessageBeingBuilt { get; private set; } = new PhoneMetadata();

            public PhoneMetadata DefaultInstanceForType => DefaultInstance;


            public bool HasGeneralDesc => MessageBeingBuilt.HasGeneralDesc;

            public PhoneNumberDesc GeneralDesc
            {
                get => MessageBeingBuilt.GeneralDesc;
                set => SetGeneralDesc(value);
            }

            public bool HasFixedLine => MessageBeingBuilt.HasFixedLine;

            public PhoneNumberDesc FixedLine
            {
                get => MessageBeingBuilt.FixedLine;
                set => SetFixedLine(value);
            }

            public bool HasMobile => MessageBeingBuilt.HasMobile;

            public PhoneNumberDesc Mobile
            {
                get => MessageBeingBuilt.Mobile;
                set => SetMobile(value);
            }

            public bool HasTollFree => MessageBeingBuilt.HasTollFree;

            public PhoneNumberDesc TollFree
            {
                get => MessageBeingBuilt.TollFree;
                set => SetTollFree(value);
            }

            public bool HasPremiumRate => MessageBeingBuilt.HasPremiumRate;

            public PhoneNumberDesc PremiumRate
            {
                get => MessageBeingBuilt.PremiumRate;
                set => SetPremiumRate(value);
            }

            public bool HasSharedCost => MessageBeingBuilt.HasSharedCost;

            public PhoneNumberDesc SharedCost
            {
                get => MessageBeingBuilt.SharedCost;
                set => SetSharedCost(value);
            }

            public bool HasPersonalNumber => MessageBeingBuilt.HasPersonalNumber;

            public PhoneNumberDesc PersonalNumber
            {
                get => MessageBeingBuilt.PersonalNumber;
                set => SetPersonalNumber(value);
            }

            public bool HasVoip => MessageBeingBuilt.HasVoip;

            public PhoneNumberDesc Voip
            {
                get => MessageBeingBuilt.Voip;
                set => SetVoip(value);
            }

            public bool HasPager => MessageBeingBuilt.HasPager;

            public PhoneNumberDesc Pager
            {
                get => MessageBeingBuilt.Pager;
                set => SetPager(value);
            }

            public bool HasUan => MessageBeingBuilt.HasUan;

            public PhoneNumberDesc Uan
            {
                get => MessageBeingBuilt.Uan;
                set => SetUan(value);
            }

            public bool HasEmergency => MessageBeingBuilt.HasEmergency;

            public PhoneNumberDesc Emergency
            {
                get => MessageBeingBuilt.Emergency;
                set => SetEmergency(value);
            }

            public bool HasVoicemail => MessageBeingBuilt.HasVoicemail;

            public PhoneNumberDesc Voicemail
            {
                get => MessageBeingBuilt.Voicemail;
                set => SetVoicemail(value);
            }

            public bool HasShortCode => MessageBeingBuilt.HasShortCode;

            public PhoneNumberDesc ShortCode
            {
                get => MessageBeingBuilt.ShortCode;
                set => SetShortCode(value);
            }

            public bool HasStandardRate => MessageBeingBuilt.HasStandardRate;

            public PhoneNumberDesc StandardRate
            {
                get => MessageBeingBuilt.StandardRate;
                set => SetStandardRate(value);
            }

            public bool HasCarrierSpecific => MessageBeingBuilt.HasCarrierSpecific;

            public PhoneNumberDesc CarrierSpecific
            {
                get => MessageBeingBuilt.CarrierSpecific;
                set => SetCarrierSpecific(value);
            }

            public bool HasSmsServices => MessageBeingBuilt.HasSmsServices;

            public PhoneNumberDesc SmsServices
            {
                get => MessageBeingBuilt.SmsServices;
                set => SetSmsServices(value);
            }

            public bool HasNoInternationalDialling => MessageBeingBuilt.HasNoInternationalDialling;

            public PhoneNumberDesc NoInternationalDialling
            {
                get => MessageBeingBuilt.NoInternationalDialling;
                set => SetNoInternationalDialling(value);
            }

            public bool HasId => MessageBeingBuilt.HasId;

            public string Id
            {
                get => MessageBeingBuilt.Id;
                set => SetId(value);
            }

            public bool HasCountryCode => MessageBeingBuilt.HasCountryCode;

            public int CountryCode
            {
                get => MessageBeingBuilt.CountryCode;
                set => SetCountryCode(value);
            }

            public bool HasInternationalPrefix => MessageBeingBuilt.HasInternationalPrefix;

            public string InternationalPrefix
            {
                get => MessageBeingBuilt.InternationalPrefix;
                set => SetInternationalPrefix(value);
            }

            public bool HasPreferredInternationalPrefix => MessageBeingBuilt.HasPreferredInternationalPrefix;

            public string PreferredInternationalPrefix
            {
                get => MessageBeingBuilt.PreferredInternationalPrefix;
                set => SetPreferredInternationalPrefix(value);
            }

            public bool HasNationalPrefix => MessageBeingBuilt.HasNationalPrefix;

            public string NationalPrefix
            {
                get => MessageBeingBuilt.NationalPrefix;
                set => SetNationalPrefix(value);
            }

            public bool HasPreferredExtnPrefix => MessageBeingBuilt.HasPreferredExtnPrefix;

            public string PreferredExtnPrefix
            {
                get => MessageBeingBuilt.PreferredExtnPrefix;
                set => SetPreferredExtnPrefix(value);
            }

            public bool HasNationalPrefixForParsing => MessageBeingBuilt.HasNationalPrefixForParsing;

            public string NationalPrefixForParsing
            {
                get => MessageBeingBuilt.NationalPrefixForParsing;
                set => SetNationalPrefixForParsing(value);
            }

            public bool HasNationalPrefixTransformRule => MessageBeingBuilt.HasNationalPrefixTransformRule;

            public string NationalPrefixTransformRule
            {
                get => MessageBeingBuilt.NationalPrefixTransformRule;
                set => SetNationalPrefixTransformRule(value);
            }

            public bool HasSameMobileAndFixedLinePattern => MessageBeingBuilt.HasSameMobileAndFixedLinePattern;

            public bool SameMobileAndFixedLinePattern
            {
                get => MessageBeingBuilt.SameMobileAndFixedLinePattern;
                set => SetSameMobileAndFixedLinePattern(value);
            }

            public scg.IList<NumberFormat> NumberFormatList => MessageBeingBuilt.numberFormat_;

            public int NumberFormatCount => MessageBeingBuilt.NumberFormatCount;

            public scg.IList<NumberFormat> IntlNumberFormatList => MessageBeingBuilt.intlNumberFormat_;

            public int IntlNumberFormatCount => MessageBeingBuilt.IntlNumberFormatCount;

            public bool HasMainCountryForCode => MessageBeingBuilt.HasMainCountryForCode;

            public bool MainCountryForCode
            {
                get => MessageBeingBuilt.MainCountryForCode;
                set => SetMainCountryForCode(value);
            }

            public bool HasLeadingDigits => MessageBeingBuilt.HasLeadingDigits;

            public string LeadingDigits
            {
                get => MessageBeingBuilt.LeadingDigits;
                set => SetLeadingDigits(value);
            }

            public bool HasLeadingZeroPossible => MessageBeingBuilt.HasLeadingZeroPossible;

            public bool LeadingZeroPossible
            {
                get => MessageBeingBuilt.LeadingZeroPossible;
                set => SetLeadingZeroPossible(value);
            }

            public bool HasMobileNumberPortableRegion => MessageBeingBuilt.HasMobileNumberPortableRegion;

            public bool MobileNumberPortableRegion
            {
                get => MessageBeingBuilt.MobileNumberPortableRegion;
                set => SetMobileNumberPortableRegion(value);
            }

            public Builder Clear()
            {
                MessageBeingBuilt = new PhoneMetadata();
                return this;
            }

            public Builder Clone()
            {
                return new Builder().MergeFrom(MessageBeingBuilt);
            }

            public PhoneMetadata Build()
            {
                return BuildPartial();
            }

            public PhoneMetadata BuildPartial()
            {
                if (MessageBeingBuilt == null)
                    throw new InvalidOperationException("build() has already been called on this Builder");


                var returnMe = MessageBeingBuilt;
                MessageBeingBuilt = null;
                return returnMe;
            }


            public Builder MergeFrom(PhoneMetadata other)
            {
                if (other == DefaultInstance) return this;
                if (other.HasGeneralDesc) MergeGeneralDesc(other.GeneralDesc);
                if (other.HasFixedLine) MergeFixedLine(other.FixedLine);
                if (other.HasMobile) MergeMobile(other.Mobile);
                if (other.HasTollFree) MergeTollFree(other.TollFree);
                if (other.HasPremiumRate) MergePremiumRate(other.PremiumRate);
                if (other.HasSharedCost) MergeSharedCost(other.SharedCost);
                if (other.HasPersonalNumber) MergePersonalNumber(other.PersonalNumber);
                if (other.HasVoip) MergeVoip(other.Voip);
                if (other.HasPager) MergePager(other.Pager);
                if (other.HasUan) MergeUan(other.Uan);
                if (other.HasEmergency) MergeEmergency(other.Emergency);
                if (other.HasVoicemail) MergeVoicemail(other.Voicemail);
                if (other.HasShortCode) MergeShortCode(other.ShortCode);
                if (other.HasStandardRate) MergeStandardRate(other.StandardRate);
                if (other.HasCarrierSpecific) MergeCarrierSpecific(other.CarrierSpecific);
                if (other.HasSmsServices) MergeSmsServices(other.SmsServices);
                if (other.HasNoInternationalDialling) MergeNoInternationalDialling(other.NoInternationalDialling);
                if (other.HasId) Id = other.Id;
                if (other.HasCountryCode) CountryCode = other.CountryCode;
                if (other.HasInternationalPrefix) InternationalPrefix = other.InternationalPrefix;
                if (other.HasPreferredInternationalPrefix)
                    PreferredInternationalPrefix = other.PreferredInternationalPrefix;
                if (other.HasNationalPrefix) NationalPrefix = other.NationalPrefix;
                if (other.HasPreferredExtnPrefix) PreferredExtnPrefix = other.PreferredExtnPrefix;
                if (other.HasNationalPrefixForParsing) NationalPrefixForParsing = other.NationalPrefixForParsing;
                if (other.HasNationalPrefixTransformRule)
                    NationalPrefixTransformRule = other.NationalPrefixTransformRule;
                if (other.HasSameMobileAndFixedLinePattern)
                    SameMobileAndFixedLinePattern = other.SameMobileAndFixedLinePattern;
                if (other.numberFormat_.Count != 0) MessageBeingBuilt.numberFormat_.AddRange(other.numberFormat_);
                if (other.intlNumberFormat_.Count != 0)
                    MessageBeingBuilt.intlNumberFormat_.AddRange(other.intlNumberFormat_);
                if (other.HasMainCountryForCode) MainCountryForCode = other.MainCountryForCode;
                if (other.HasLeadingDigits) LeadingDigits = other.LeadingDigits;
                if (other.HasLeadingZeroPossible) LeadingZeroPossible = other.LeadingZeroPossible;
                if (other.HasMobileNumberPortableRegion) MobileNumberPortableRegion = other.MobileNumberPortableRegion;
                return this;
            }

            public Builder SetGeneralDesc(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasGeneralDesc = true;
                MessageBeingBuilt.GeneralDesc = value;
                return this;
            }

            public Builder SetGeneralDesc(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasGeneralDesc = true;
                MessageBeingBuilt.GeneralDesc = builderForValue.Build();
                return this;
            }

            public Builder MergeGeneralDesc(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasGeneralDesc &&
                    MessageBeingBuilt.GeneralDesc != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.GeneralDesc = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.GeneralDesc)
                        .MergeFrom(value).BuildPartial();
                else MessageBeingBuilt.GeneralDesc = value;
                MessageBeingBuilt.HasGeneralDesc = true;
                return this;
            }

            public Builder ClearGeneralDesc()
            {
                MessageBeingBuilt.HasGeneralDesc = false;
                MessageBeingBuilt.GeneralDesc = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetFixedLine(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasFixedLine = true;
                MessageBeingBuilt.FixedLine = value;
                return this;
            }

            public Builder SetFixedLine(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasFixedLine = true;
                MessageBeingBuilt.FixedLine = builderForValue.Build();
                return this;
            }

            public Builder MergeFixedLine(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasFixedLine &&
                    MessageBeingBuilt.FixedLine != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.FixedLine = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.FixedLine)
                        .MergeFrom(value).BuildPartial();
                else MessageBeingBuilt.FixedLine = value;
                MessageBeingBuilt.HasFixedLine = true;
                return this;
            }

            public Builder ClearFixedLine()
            {
                MessageBeingBuilt.HasFixedLine = false;
                MessageBeingBuilt.FixedLine = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetMobile(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasMobile = true;
                MessageBeingBuilt.Mobile = value;
                return this;
            }

            public Builder SetMobile(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasMobile = true;
                MessageBeingBuilt.Mobile = builderForValue.Build();
                return this;
            }

            public Builder MergeMobile(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasMobile &&
                    MessageBeingBuilt.Mobile != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.Mobile = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.Mobile).MergeFrom(value)
                        .BuildPartial();
                else MessageBeingBuilt.Mobile = value;
                MessageBeingBuilt.HasMobile = true;
                return this;
            }

            public Builder ClearMobile()
            {
                MessageBeingBuilt.HasMobile = false;
                MessageBeingBuilt.Mobile = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetTollFree(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasTollFree = true;
                MessageBeingBuilt.TollFree = value;
                return this;
            }

            public Builder SetTollFree(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasTollFree = true;
                MessageBeingBuilt.TollFree = builderForValue.Build();
                return this;
            }

            public Builder MergeTollFree(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasTollFree &&
                    MessageBeingBuilt.TollFree != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.TollFree = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.TollFree)
                        .MergeFrom(value).BuildPartial();
                else MessageBeingBuilt.TollFree = value;
                MessageBeingBuilt.HasTollFree = true;
                return this;
            }

            public Builder ClearTollFree()
            {
                MessageBeingBuilt.HasTollFree = false;
                MessageBeingBuilt.TollFree = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetPremiumRate(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasPremiumRate = true;
                MessageBeingBuilt.PremiumRate = value;
                return this;
            }

            public Builder SetPremiumRate(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasPremiumRate = true;
                MessageBeingBuilt.PremiumRate = builderForValue.Build();
                return this;
            }

            public Builder MergePremiumRate(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasPremiumRate &&
                    MessageBeingBuilt.PremiumRate != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.PremiumRate = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.PremiumRate)
                        .MergeFrom(value).BuildPartial();
                else MessageBeingBuilt.PremiumRate = value;
                MessageBeingBuilt.HasPremiumRate = true;
                return this;
            }

            public Builder ClearPremiumRate()
            {
                MessageBeingBuilt.HasPremiumRate = false;
                MessageBeingBuilt.PremiumRate = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetSharedCost(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasSharedCost = true;
                MessageBeingBuilt.SharedCost = value;
                return this;
            }

            public Builder SetSharedCost(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasSharedCost = true;
                MessageBeingBuilt.SharedCost = builderForValue.Build();
                return this;
            }

            public Builder MergeSharedCost(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasSharedCost &&
                    MessageBeingBuilt.SharedCost != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.SharedCost = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.SharedCost)
                        .MergeFrom(value).BuildPartial();
                else MessageBeingBuilt.SharedCost = value;
                MessageBeingBuilt.HasSharedCost = true;
                return this;
            }

            public Builder ClearSharedCost()
            {
                MessageBeingBuilt.HasSharedCost = false;
                MessageBeingBuilt.SharedCost = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetPersonalNumber(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasPersonalNumber = true;
                MessageBeingBuilt.PersonalNumber = value;
                return this;
            }

            public Builder SetPersonalNumber(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasPersonalNumber = true;
                MessageBeingBuilt.PersonalNumber = builderForValue.Build();
                return this;
            }

            public Builder MergePersonalNumber(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasPersonalNumber &&
                    MessageBeingBuilt.PersonalNumber != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.PersonalNumber = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.PersonalNumber)
                        .MergeFrom(value).BuildPartial();
                else MessageBeingBuilt.PersonalNumber = value;
                MessageBeingBuilt.HasPersonalNumber = true;
                return this;
            }

            public Builder ClearPersonalNumber()
            {
                MessageBeingBuilt.HasPersonalNumber = false;
                MessageBeingBuilt.PersonalNumber = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetVoip(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasVoip = true;
                MessageBeingBuilt.Voip = value;
                return this;
            }

            public Builder SetVoip(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasVoip = true;
                MessageBeingBuilt.Voip = builderForValue.Build();
                return this;
            }

            public Builder MergeVoip(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasVoip &&
                    MessageBeingBuilt.Voip != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.Voip = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.Voip).MergeFrom(value)
                        .BuildPartial();
                else MessageBeingBuilt.Voip = value;
                MessageBeingBuilt.HasVoip = true;
                return this;
            }

            public Builder ClearVoip()
            {
                MessageBeingBuilt.HasVoip = false;
                MessageBeingBuilt.Voip = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetPager(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasPager = true;
                MessageBeingBuilt.Pager = value;
                return this;
            }

            public Builder SetPager(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasPager = true;
                MessageBeingBuilt.Pager = builderForValue.Build();
                return this;
            }

            public Builder MergePager(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasPager &&
                    MessageBeingBuilt.Pager != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.Pager = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.Pager).MergeFrom(value)
                        .BuildPartial();
                else MessageBeingBuilt.Pager = value;
                MessageBeingBuilt.HasPager = true;
                return this;
            }

            public Builder ClearPager()
            {
                MessageBeingBuilt.HasPager = false;
                MessageBeingBuilt.Pager = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetUan(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasUan = true;
                MessageBeingBuilt.Uan = value;
                return this;
            }

            public Builder SetUan(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasUan = true;
                MessageBeingBuilt.Uan = builderForValue.Build();
                return this;
            }

            public Builder MergeUan(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasUan &&
                    MessageBeingBuilt.Uan != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.Uan = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.Uan).MergeFrom(value)
                        .BuildPartial();
                else MessageBeingBuilt.Uan = value;
                MessageBeingBuilt.HasUan = true;
                return this;
            }

            public Builder ClearUan()
            {
                MessageBeingBuilt.HasUan = false;
                MessageBeingBuilt.Uan = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetEmergency(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasEmergency = true;
                MessageBeingBuilt.Emergency = value;
                return this;
            }

            public Builder SetEmergency(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasEmergency = true;
                MessageBeingBuilt.Emergency = builderForValue.Build();
                return this;
            }

            public Builder MergeEmergency(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasEmergency &&
                    MessageBeingBuilt.Emergency != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.Emergency = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.Emergency)
                        .MergeFrom(value).BuildPartial();
                else MessageBeingBuilt.Emergency = value;
                MessageBeingBuilt.HasEmergency = true;
                return this;
            }

            public Builder ClearEmergency()
            {
                MessageBeingBuilt.HasEmergency = false;
                MessageBeingBuilt.Emergency = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetVoicemail(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasVoicemail = true;
                MessageBeingBuilt.Voicemail = value;
                return this;
            }

            public Builder SetVoicemail(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasVoicemail = true;
                MessageBeingBuilt.Voicemail = builderForValue.Build();
                return this;
            }

            public Builder MergeVoicemail(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasVoicemail &&
                    MessageBeingBuilt.Voicemail != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.Voicemail = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.Voicemail)
                        .MergeFrom(value).BuildPartial();
                else MessageBeingBuilt.Voicemail = value;
                MessageBeingBuilt.HasVoicemail = true;
                return this;
            }

            public Builder ClearVoicemail()
            {
                MessageBeingBuilt.HasVoicemail = false;
                MessageBeingBuilt.Voicemail = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetShortCode(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasShortCode = true;
                MessageBeingBuilt.ShortCode = value;
                return this;
            }

            public Builder SetShortCode(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasShortCode = true;
                MessageBeingBuilt.ShortCode = builderForValue.Build();
                return this;
            }

            public Builder MergeShortCode(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasShortCode &&
                    MessageBeingBuilt.ShortCode != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.ShortCode = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.ShortCode)
                        .MergeFrom(value).BuildPartial();
                else MessageBeingBuilt.ShortCode = value;
                MessageBeingBuilt.HasShortCode = true;
                return this;
            }

            public Builder ClearShortCode()
            {
                MessageBeingBuilt.HasShortCode = false;
                MessageBeingBuilt.ShortCode = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetStandardRate(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasStandardRate = true;
                MessageBeingBuilt.StandardRate = value;
                return this;
            }

            public Builder SetStandardRate(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasStandardRate = true;
                MessageBeingBuilt.StandardRate = builderForValue.Build();
                return this;
            }

            public Builder MergeStandardRate(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasStandardRate &&
                    MessageBeingBuilt.StandardRate != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.StandardRate = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.StandardRate)
                        .MergeFrom(value).BuildPartial();
                else MessageBeingBuilt.StandardRate = value;
                MessageBeingBuilt.HasStandardRate = true;
                return this;
            }

            public Builder ClearStandardRate()
            {
                MessageBeingBuilt.HasStandardRate = false;
                MessageBeingBuilt.StandardRate = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetCarrierSpecific(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasCarrierSpecific = true;
                MessageBeingBuilt.CarrierSpecific = value;
                return this;
            }

            public Builder SetCarrierSpecific(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasCarrierSpecific = true;
                MessageBeingBuilt.CarrierSpecific = builderForValue.Build();
                return this;
            }

            public Builder MergeCarrierSpecific(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasCarrierSpecific &&
                    MessageBeingBuilt.CarrierSpecific != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.CarrierSpecific = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.CarrierSpecific)
                        .MergeFrom(value).BuildPartial();
                else MessageBeingBuilt.CarrierSpecific = value;
                MessageBeingBuilt.HasCarrierSpecific = true;
                return this;
            }

            public Builder ClearCarrierSpecific()
            {
                MessageBeingBuilt.HasCarrierSpecific = false;
                MessageBeingBuilt.CarrierSpecific = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetSmsServices(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasSmsServices = true;
                MessageBeingBuilt.SmsServices = value;
                return this;
            }

            public Builder SetSmsServices(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasSmsServices = true;
                MessageBeingBuilt.SmsServices = builderForValue.Build();
                return this;
            }

            public Builder MergeSmsServices(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasSmsServices &&
                    MessageBeingBuilt.SmsServices != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.SmsServices = PhoneNumberDesc.CreateBuilder(MessageBeingBuilt.SmsServices)
                        .MergeFrom(value).BuildPartial();
                else MessageBeingBuilt.SmsServices = value;
                MessageBeingBuilt.HasSmsServices = true;
                return this;
            }

            public Builder ClearSmsServices()
            {
                MessageBeingBuilt.HasSmsServices = false;
                MessageBeingBuilt.SmsServices = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetNoInternationalDialling(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasNoInternationalDialling = true;
                MessageBeingBuilt.NoInternationalDialling = value;
                return this;
            }

            public Builder SetNoInternationalDialling(PhoneNumberDesc.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.HasNoInternationalDialling = true;
                MessageBeingBuilt.NoInternationalDialling = builderForValue.Build();
                return this;
            }

            public Builder MergeNoInternationalDialling(PhoneNumberDesc value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                if (MessageBeingBuilt.HasNoInternationalDialling &&
                    MessageBeingBuilt.NoInternationalDialling != PhoneNumberDesc.DefaultInstance)
                    MessageBeingBuilt.NoInternationalDialling = PhoneNumberDesc
                        .CreateBuilder(MessageBeingBuilt.NoInternationalDialling).MergeFrom(value).BuildPartial();
                else MessageBeingBuilt.NoInternationalDialling = value;
                MessageBeingBuilt.HasNoInternationalDialling = true;
                return this;
            }

            public Builder ClearNoInternationalDialling()
            {
                MessageBeingBuilt.HasNoInternationalDialling = false;
                MessageBeingBuilt.NoInternationalDialling = PhoneNumberDesc.DefaultInstance;
                return this;
            }

            public Builder SetId(string value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasId = true;
                MessageBeingBuilt.Id = value;
                return this;
            }

            public Builder ClearId()
            {
                MessageBeingBuilt.HasId = false;
                MessageBeingBuilt.Id = "";
                return this;
            }

            public Builder SetCountryCode(int value)
            {
                MessageBeingBuilt.HasCountryCode = true;
                MessageBeingBuilt.CountryCode = value;
                return this;
            }

            public Builder ClearCountryCode()
            {
                MessageBeingBuilt.HasCountryCode = false;
                MessageBeingBuilt.CountryCode = 0;
                return this;
            }

            public Builder SetInternationalPrefix(string value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasInternationalPrefix = true;
                MessageBeingBuilt.InternationalPrefix = value;
                return this;
            }

            public Builder ClearInternationalPrefix()
            {
                MessageBeingBuilt.HasInternationalPrefix = false;
                MessageBeingBuilt.InternationalPrefix = "";
                return this;
            }

            public Builder SetPreferredInternationalPrefix(string value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasPreferredInternationalPrefix = true;
                MessageBeingBuilt.PreferredInternationalPrefix = value;
                return this;
            }

            public Builder ClearPreferredInternationalPrefix()
            {
                MessageBeingBuilt.HasPreferredInternationalPrefix = false;
                MessageBeingBuilt.PreferredInternationalPrefix = "";
                return this;
            }

            public Builder SetNationalPrefix(string value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasNationalPrefix = true;
                MessageBeingBuilt.NationalPrefix = value;
                return this;
            }

            public Builder ClearNationalPrefix()
            {
                MessageBeingBuilt.HasNationalPrefix = false;
                MessageBeingBuilt.NationalPrefix = "";
                return this;
            }

            public Builder SetPreferredExtnPrefix(string value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasPreferredExtnPrefix = true;
                MessageBeingBuilt.PreferredExtnPrefix = value;
                return this;
            }

            public Builder ClearPreferredExtnPrefix()
            {
                MessageBeingBuilt.HasPreferredExtnPrefix = false;
                MessageBeingBuilt.PreferredExtnPrefix = "";
                return this;
            }

            public Builder SetNationalPrefixForParsing(string value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasNationalPrefixForParsing = true;
                MessageBeingBuilt.NationalPrefixForParsing = value;
                return this;
            }

            public Builder ClearNationalPrefixForParsing()
            {
                MessageBeingBuilt.HasNationalPrefixForParsing = false;
                MessageBeingBuilt.NationalPrefixForParsing = "";
                return this;
            }

            public Builder SetNationalPrefixTransformRule(string value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasNationalPrefixTransformRule = true;
                MessageBeingBuilt.NationalPrefixTransformRule = value;
                return this;
            }

            public Builder ClearNationalPrefixTransformRule()
            {
                MessageBeingBuilt.HasNationalPrefixTransformRule = false;
                MessageBeingBuilt.NationalPrefixTransformRule = "";
                return this;
            }

            public Builder SetSameMobileAndFixedLinePattern(bool value)
            {
                MessageBeingBuilt.HasSameMobileAndFixedLinePattern = true;
                MessageBeingBuilt.SameMobileAndFixedLinePattern = value;
                return this;
            }

            public Builder ClearSameMobileAndFixedLinePattern()
            {
                MessageBeingBuilt.HasSameMobileAndFixedLinePattern = false;
                MessageBeingBuilt.SameMobileAndFixedLinePattern = false;
                return this;
            }

            public NumberFormat GetNumberFormat(int index)
            {
                return MessageBeingBuilt.GetNumberFormat(index);
            }

            public Builder SetNumberFormat(int index, NumberFormat value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.numberFormat_[index] = value;
                return this;
            }

            public Builder SetNumberFormat(int index, NumberFormat.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.numberFormat_[index] = builderForValue.Build();
                return this;
            }

            public Builder AddNumberFormat(NumberFormat value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.numberFormat_.Add(value);
                return this;
            }

            public Builder AddNumberFormat(NumberFormat.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.numberFormat_.Add(builderForValue.Build());
                return this;
            }

            public Builder AddRangeNumberFormat(scg.IEnumerable<NumberFormat> values)
            {
                MessageBeingBuilt.numberFormat_.AddRange(values);
                return this;
            }

            public Builder ClearNumberFormat()
            {
                MessageBeingBuilt.numberFormat_.Clear();
                return this;
            }

            public NumberFormat GetIntlNumberFormat(int index)
            {
                return MessageBeingBuilt.GetIntlNumberFormat(index);
            }

            public Builder SetIntlNumberFormat(int index, NumberFormat value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.intlNumberFormat_[index] = value;
                return this;
            }

            public Builder SetIntlNumberFormat(int index, NumberFormat.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.intlNumberFormat_[index] = builderForValue.Build();
                return this;
            }

            public Builder AddIntlNumberFormat(NumberFormat value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.intlNumberFormat_.Add(value);
                return this;
            }

            public Builder AddIntlNumberFormat(NumberFormat.Builder builderForValue)
            {
                if (builderForValue == null) throw new ArgumentNullException(nameof(builderForValue));
                MessageBeingBuilt.intlNumberFormat_.Add(builderForValue.Build());
                return this;
            }

            public Builder AddRangeIntlNumberFormat(scg.IEnumerable<NumberFormat> values)
            {
                MessageBeingBuilt.intlNumberFormat_.AddRange(values);
                return this;
            }

            public Builder ClearIntlNumberFormat()
            {
                MessageBeingBuilt.intlNumberFormat_.Clear();
                return this;
            }

            public Builder SetMainCountryForCode(bool value)
            {
                MessageBeingBuilt.HasMainCountryForCode = true;
                MessageBeingBuilt.MainCountryForCode = value;
                return this;
            }

            public Builder ClearMainCountryForCode()
            {
                MessageBeingBuilt.HasMainCountryForCode = false;
                MessageBeingBuilt.MainCountryForCode = false;
                return this;
            }

            public Builder SetLeadingDigits(string value)
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                MessageBeingBuilt.HasLeadingDigits = true;
                MessageBeingBuilt.LeadingDigits = value;
                return this;
            }

            public Builder ClearLeadingDigits()
            {
                MessageBeingBuilt.HasLeadingDigits = false;
                MessageBeingBuilt.LeadingDigits = "";
                return this;
            }

            public Builder SetLeadingZeroPossible(bool value)
            {
                MessageBeingBuilt.HasLeadingZeroPossible = true;
                MessageBeingBuilt.LeadingZeroPossible = value;
                return this;
            }

            public Builder ClearLeadingZeroPossible()
            {
                MessageBeingBuilt.HasLeadingZeroPossible = false;
                MessageBeingBuilt.LeadingZeroPossible = false;
                return this;
            }

            public Builder SetMobileNumberPortableRegion(bool value)
            {
                MessageBeingBuilt.HasMobileNumberPortableRegion = true;
                MessageBeingBuilt.MobileNumberPortableRegion = value;
                return this;
            }

            public Builder ClearMobileNumberPortableRegion()
            {
                MessageBeingBuilt.HasMobileNumberPortableRegion = false;
                MessageBeingBuilt.MobileNumberPortableRegion = false;
                return this;
            }
        }


        #region Lite runtime methods

        public override int GetHashCode()
        {
            var hash = GetType().GetHashCode();
            if (HasGeneralDesc) hash ^= GeneralDesc.GetHashCode();
            if (HasFixedLine) hash ^= FixedLine.GetHashCode();
            if (HasMobile) hash ^= Mobile.GetHashCode();
            if (HasTollFree) hash ^= TollFree.GetHashCode();
            if (HasPremiumRate) hash ^= PremiumRate.GetHashCode();
            if (HasSharedCost) hash ^= SharedCost.GetHashCode();
            if (HasPersonalNumber) hash ^= PersonalNumber.GetHashCode();
            if (HasVoip) hash ^= Voip.GetHashCode();
            if (HasPager) hash ^= Pager.GetHashCode();
            if (HasUan) hash ^= Uan.GetHashCode();
            if (HasEmergency) hash ^= Emergency.GetHashCode();
            if (HasVoicemail) hash ^= Voicemail.GetHashCode();
            if (HasShortCode) hash ^= ShortCode.GetHashCode();
            if (HasStandardRate) hash ^= StandardRate.GetHashCode();
            if (HasCarrierSpecific) hash ^= CarrierSpecific.GetHashCode();
            if (HasSmsServices) hash ^= SmsServices.GetHashCode();
            if (HasNoInternationalDialling) hash ^= NoInternationalDialling.GetHashCode();
            if (HasId) hash ^= Id.GetHashCode();
            if (HasCountryCode) hash ^= CountryCode.GetHashCode();
            if (HasInternationalPrefix) hash ^= InternationalPrefix.GetHashCode();
            if (HasPreferredInternationalPrefix) hash ^= PreferredInternationalPrefix.GetHashCode();
            if (HasNationalPrefix) hash ^= NationalPrefix.GetHashCode();
            if (HasPreferredExtnPrefix) hash ^= PreferredExtnPrefix.GetHashCode();
            if (HasNationalPrefixForParsing) hash ^= NationalPrefixForParsing.GetHashCode();
            if (HasNationalPrefixTransformRule) hash ^= NationalPrefixTransformRule.GetHashCode();
            if (HasSameMobileAndFixedLinePattern) hash ^= SameMobileAndFixedLinePattern.GetHashCode();
            foreach (var i in numberFormat_)
                hash ^= i.GetHashCode();
            foreach (var i in intlNumberFormat_)
                hash ^= i.GetHashCode();
            if (HasMainCountryForCode) hash ^= MainCountryForCode.GetHashCode();
            if (HasLeadingDigits) hash ^= LeadingDigits.GetHashCode();
            if (HasLeadingZeroPossible) hash ^= LeadingZeroPossible.GetHashCode();
            if (HasMobileNumberPortableRegion) hash ^= MobileNumberPortableRegion.GetHashCode();
            return hash;
        }

        public override bool Equals(object obj)
        {
            var other = obj as PhoneMetadata;
            if (other == null) return false;
            if (HasGeneralDesc != other.HasGeneralDesc ||
                HasGeneralDesc && !GeneralDesc.Equals(other.GeneralDesc)) return false;
            if (HasFixedLine != other.HasFixedLine || HasFixedLine && !FixedLine.Equals(other.FixedLine)) return false;
            if (HasMobile != other.HasMobile || HasMobile && !Mobile.Equals(other.Mobile)) return false;
            if (HasTollFree != other.HasTollFree || HasTollFree && !TollFree.Equals(other.TollFree)) return false;
            if (HasPremiumRate != other.HasPremiumRate ||
                HasPremiumRate && !PremiumRate.Equals(other.PremiumRate)) return false;
            if (HasSharedCost != other.HasSharedCost ||
                HasSharedCost && !SharedCost.Equals(other.SharedCost)) return false;
            if (HasPersonalNumber != other.HasPersonalNumber ||
                HasPersonalNumber && !PersonalNumber.Equals(other.PersonalNumber)) return false;
            if (HasVoip != other.HasVoip || HasVoip && !Voip.Equals(other.Voip)) return false;
            if (HasPager != other.HasPager || HasPager && !Pager.Equals(other.Pager)) return false;
            if (HasUan != other.HasUan || HasUan && !Uan.Equals(other.Uan)) return false;
            if (HasEmergency != other.HasEmergency || HasEmergency && !Emergency.Equals(other.Emergency)) return false;
            if (HasVoicemail != other.HasVoicemail || HasVoicemail && !Voicemail.Equals(other.Voicemail)) return false;
            if (HasShortCode != other.HasShortCode || HasShortCode && !ShortCode.Equals(other.ShortCode)) return false;
            if (HasStandardRate != other.HasStandardRate ||
                HasStandardRate && !StandardRate.Equals(other.StandardRate)) return false;
            if (HasCarrierSpecific != other.HasCarrierSpecific ||
                HasCarrierSpecific && !CarrierSpecific.Equals(other.CarrierSpecific)) return false;
            if (HasSmsServices != other.HasSmsServices ||
                HasSmsServices && !SmsServices.Equals(other.SmsServices)) return false;
            if (HasNoInternationalDialling != other.HasNoInternationalDialling || HasNoInternationalDialling &&
                !NoInternationalDialling.Equals(other.NoInternationalDialling)) return false;
            if (HasId != other.HasId || HasId && !Id.Equals(other.Id)) return false;
            if (HasCountryCode != other.HasCountryCode ||
                HasCountryCode && !CountryCode.Equals(other.CountryCode)) return false;
            if (HasInternationalPrefix != other.HasInternationalPrefix || HasInternationalPrefix &&
                !InternationalPrefix.Equals(other.InternationalPrefix)) return false;
            if (HasPreferredInternationalPrefix != other.HasPreferredInternationalPrefix ||
                HasPreferredInternationalPrefix &&
                !PreferredInternationalPrefix.Equals(other.PreferredInternationalPrefix)) return false;
            if (HasNationalPrefix != other.HasNationalPrefix ||
                HasNationalPrefix && !NationalPrefix.Equals(other.NationalPrefix)) return false;
            if (HasPreferredExtnPrefix != other.HasPreferredExtnPrefix || HasPreferredExtnPrefix &&
                !PreferredExtnPrefix.Equals(other.PreferredExtnPrefix)) return false;
            if (HasNationalPrefixForParsing != other.HasNationalPrefixForParsing || HasNationalPrefixForParsing &&
                !NationalPrefixForParsing.Equals(other.NationalPrefixForParsing)) return false;
            if (HasNationalPrefixTransformRule != other.HasNationalPrefixTransformRule ||
                HasNationalPrefixTransformRule &&
                !NationalPrefixTransformRule.Equals(other.NationalPrefixTransformRule)) return false;
            if (HasSameMobileAndFixedLinePattern != other.HasSameMobileAndFixedLinePattern ||
                HasSameMobileAndFixedLinePattern &&
                !SameMobileAndFixedLinePattern.Equals(other.SameMobileAndFixedLinePattern)) return false;
            if (numberFormat_.Count != other.numberFormat_.Count) return false;
            for (var ix = 0; ix < numberFormat_.Count; ix++)
                if (!numberFormat_[ix].Equals(other.numberFormat_[ix])) return false;
            if (intlNumberFormat_.Count != other.intlNumberFormat_.Count) return false;
            for (var ix = 0; ix < intlNumberFormat_.Count; ix++)
                if (!intlNumberFormat_[ix].Equals(other.intlNumberFormat_[ix])) return false;
            if (HasMainCountryForCode != other.HasMainCountryForCode || HasMainCountryForCode &&
                !MainCountryForCode.Equals(other.MainCountryForCode)) return false;
            if (HasLeadingDigits != other.HasLeadingDigits ||
                HasLeadingDigits && !LeadingDigits.Equals(other.LeadingDigits)) return false;
            if (HasLeadingZeroPossible != other.HasLeadingZeroPossible || HasLeadingZeroPossible &&
                !LeadingZeroPossible.Equals(other.LeadingZeroPossible)) return false;
            if (HasMobileNumberPortableRegion != other.HasMobileNumberPortableRegion || HasMobileNumberPortableRegion &&
                !MobileNumberPortableRegion.Equals(other.MobileNumberPortableRegion)) return false;
            return true;
        }

        #endregion
    }

    #endregion
}