// Generated by ProtoGen, Version=2.3.0.277, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!

using scg = global::System.Collections.Generic;
namespace PhoneNumbers {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
  public static partial class Phonemetadata {
  
    
    #region Static variables
    #endregion
    #region Extensions
    internal static readonly object Descriptor;
    static Phonemetadata() {
      Descriptor = null;
    }
    #endregion
    
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
  public partial class NumberFormat {
    private static readonly NumberFormat defaultInstance = new Builder().BuildPartial();
    public static NumberFormat DefaultInstance {
      get { return defaultInstance; }
    }
    
    public NumberFormat DefaultInstanceForType {
      get { return defaultInstance; }
    }
    
    protected NumberFormat ThisMessage {
      get { return this; }
    }
    
    public const int PatternFieldNumber = 1;
    private bool hasPattern;
    private string pattern_ = "";
    public bool HasPattern {
      get { return hasPattern; }
    }
    public string Pattern {
      get { return pattern_; }
    }
    
    public const int FormatFieldNumber = 2;
    private bool hasFormat;
    private string format_ = "";
    public bool HasFormat {
      get { return hasFormat; }
    }
    public string Format {
      get { return format_; }
    }
    
    public const int LeadingDigitsPatternFieldNumber = 3;
    private scg::List<string> leadingDigitsPattern_ = new scg::List<string>();
    public scg::IList<string> LeadingDigitsPatternList {
      get { return leadingDigitsPattern_; }
    }
    public int LeadingDigitsPatternCount {
      get { return leadingDigitsPattern_.Count; }
    }
    public string GetLeadingDigitsPattern(int index) {
      return leadingDigitsPattern_[index];
    }
    
    public const int NationalPrefixFormattingRuleFieldNumber = 4;
    private bool hasNationalPrefixFormattingRule;
    private string nationalPrefixFormattingRule_ = "";
    public bool HasNationalPrefixFormattingRule {
      get { return hasNationalPrefixFormattingRule; }
    }
    public string NationalPrefixFormattingRule {
      get { return nationalPrefixFormattingRule_; }
    }
    
    public const int NationalPrefixOptionalWhenFormattingFieldNumber = 6;
    private bool hasNationalPrefixOptionalWhenFormatting;
    private bool nationalPrefixOptionalWhenFormatting_ = false;
    public bool HasNationalPrefixOptionalWhenFormatting {
      get { return hasNationalPrefixOptionalWhenFormatting; }
    }
    public bool NationalPrefixOptionalWhenFormatting {
      get { return nationalPrefixOptionalWhenFormatting_; }
    }
    
    public const int DomesticCarrierCodeFormattingRuleFieldNumber = 5;
    private bool hasDomesticCarrierCodeFormattingRule;
    private string domesticCarrierCodeFormattingRule_ = "";
    public bool HasDomesticCarrierCodeFormattingRule {
      get { return hasDomesticCarrierCodeFormattingRule; }
    }
    public string DomesticCarrierCodeFormattingRule {
      get { return domesticCarrierCodeFormattingRule_; }
    }
    
    public bool IsInitialized {
      get {
        if (!hasPattern) return false;
        if (!hasFormat) return false;
        return true;
      }
    }
    
    
    
    
    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      if (hasPattern) hash ^= pattern_.GetHashCode();
      if (hasFormat) hash ^= format_.GetHashCode();
      foreach(string i in leadingDigitsPattern_)
        hash ^= i.GetHashCode();
      if (hasNationalPrefixFormattingRule) hash ^= nationalPrefixFormattingRule_.GetHashCode();
      if (hasNationalPrefixOptionalWhenFormatting) hash ^= nationalPrefixOptionalWhenFormatting_.GetHashCode();
      if (hasDomesticCarrierCodeFormattingRule) hash ^= domesticCarrierCodeFormattingRule_.GetHashCode();
      return hash;
    }
    
    public override bool Equals(object obj) {
      NumberFormat other = obj as NumberFormat;
      if (other == null) return false;
      if (hasPattern != other.hasPattern || (hasPattern && !pattern_.Equals(other.pattern_))) return false;
      if (hasFormat != other.hasFormat || (hasFormat && !format_.Equals(other.format_))) return false;
      if(leadingDigitsPattern_.Count != other.leadingDigitsPattern_.Count) return false;
      for(int ix=0; ix < leadingDigitsPattern_.Count; ix++)
        if(!leadingDigitsPattern_[ix].Equals(other.leadingDigitsPattern_[ix])) return false;
      if (hasNationalPrefixFormattingRule != other.hasNationalPrefixFormattingRule || (hasNationalPrefixFormattingRule && !nationalPrefixFormattingRule_.Equals(other.nationalPrefixFormattingRule_))) return false;
      if (hasNationalPrefixOptionalWhenFormatting != other.hasNationalPrefixOptionalWhenFormatting || (hasNationalPrefixOptionalWhenFormatting && !nationalPrefixOptionalWhenFormatting_.Equals(other.nationalPrefixOptionalWhenFormatting_))) return false;
      if (hasDomesticCarrierCodeFormattingRule != other.hasDomesticCarrierCodeFormattingRule || (hasDomesticCarrierCodeFormattingRule && !domesticCarrierCodeFormattingRule_.Equals(other.domesticCarrierCodeFormattingRule_))) return false;
      return true;
    }
    
    #endregion
    
    public static Builder CreateBuilder() { return new Builder(); }
    public Builder ToBuilder() { return CreateBuilder(this); }
    public Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(NumberFormat prototype) {
      return (Builder) new Builder().MergeFrom(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public partial class Builder {
      protected Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {}
      
      NumberFormat result = new NumberFormat();
      
      protected NumberFormat MessageBeingBuilt {
        get { return result; }
      }
      
      public Builder Clear() {
        result = new NumberFormat();
        return this;
      }
      
      public Builder Clone() {
        return new Builder().MergeFrom(result);
      }
      
      public NumberFormat DefaultInstanceForType {
        get { return global::PhoneNumbers.NumberFormat.DefaultInstance; }
      }
      
      public NumberFormat Build() { return BuildPartial(); }
      
      public NumberFormat BuildPartial() {
        if (result == null) {
          throw new global::System.InvalidOperationException("build() has already been called on this Builder");
        }

        NumberFormat returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      public Builder MergeFrom(NumberFormat other) {
        if (other == global::PhoneNumbers.NumberFormat.DefaultInstance) return this;
        if (other.HasPattern) {
          Pattern = other.Pattern;
        }
        if (other.HasFormat) {
          Format = other.Format;
        }
        if (other.leadingDigitsPattern_.Count != 0) {
           result.leadingDigitsPattern_.AddRange(other.leadingDigitsPattern_);
        }
        if (other.HasNationalPrefixFormattingRule) {
          NationalPrefixFormattingRule = other.NationalPrefixFormattingRule;
        }
        if (other.HasNationalPrefixOptionalWhenFormatting) {
          NationalPrefixOptionalWhenFormatting = other.NationalPrefixOptionalWhenFormatting;
        }
        if (other.HasDomesticCarrierCodeFormattingRule) {
          DomesticCarrierCodeFormattingRule = other.DomesticCarrierCodeFormattingRule;
        }
        return this;
      }
      
      
      
      
      public bool HasPattern {
        get { return result.HasPattern; }
      }
      public string Pattern {
        get { return result.Pattern; }
        set { SetPattern(value); }
      }
      public Builder SetPattern(string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasPattern = true;
        result.pattern_ = value;
        return this;
      }
      public Builder ClearPattern() {
        result.hasPattern = false;
        result.pattern_ = "";
        return this;
      }
      
      public bool HasFormat {
        get { return result.HasFormat; }
      }
      public string Format {
        get { return result.Format; }
        set { SetFormat(value); }
      }
      public Builder SetFormat(string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasFormat = true;
        result.format_ = value;
        return this;
      }
      public Builder ClearFormat() {
        result.hasFormat = false;
        result.format_ = "";
        return this;
      }
      
      public scg::IList<string> LeadingDigitsPatternList {
        get { return result.leadingDigitsPattern_; }
      }
      public int LeadingDigitsPatternCount {
        get { return result.LeadingDigitsPatternCount; }
      }
      public string GetLeadingDigitsPattern(int index) {
        return result.GetLeadingDigitsPattern(index);
      }
      public Builder SetLeadingDigitsPattern(int index, string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.leadingDigitsPattern_[index] = value;
        return this;
      }
      public Builder AddLeadingDigitsPattern(string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.leadingDigitsPattern_.Add(value);
        return this;
      }
      public Builder AddRangeLeadingDigitsPattern(scg::IEnumerable<string> values) {
         result.leadingDigitsPattern_.AddRange(values);
        return this;
      }
      public Builder ClearLeadingDigitsPattern() {
        result.leadingDigitsPattern_.Clear();
        return this;
      }
      
      public bool HasNationalPrefixFormattingRule {
        get { return result.HasNationalPrefixFormattingRule; }
      }
      public string NationalPrefixFormattingRule {
        get { return result.NationalPrefixFormattingRule; }
        set { SetNationalPrefixFormattingRule(value); }
      }
      public Builder SetNationalPrefixFormattingRule(string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasNationalPrefixFormattingRule = true;
        result.nationalPrefixFormattingRule_ = value;
        return this;
      }
      public Builder ClearNationalPrefixFormattingRule() {
        result.hasNationalPrefixFormattingRule = false;
        result.nationalPrefixFormattingRule_ = "";
        return this;
      }
      
      public bool HasNationalPrefixOptionalWhenFormatting {
        get { return result.HasNationalPrefixOptionalWhenFormatting; }
      }
      public bool NationalPrefixOptionalWhenFormatting {
        get { return result.NationalPrefixOptionalWhenFormatting; }
        set { SetNationalPrefixOptionalWhenFormatting(value); }
      }
      public Builder SetNationalPrefixOptionalWhenFormatting(bool value) {
        result.hasNationalPrefixOptionalWhenFormatting = true;
        result.nationalPrefixOptionalWhenFormatting_ = value;
        return this;
      }
      public Builder ClearNationalPrefixOptionalWhenFormatting() {
        result.hasNationalPrefixOptionalWhenFormatting = false;
        result.nationalPrefixOptionalWhenFormatting_ = false;
        return this;
      }
      
      public bool HasDomesticCarrierCodeFormattingRule {
        get { return result.HasDomesticCarrierCodeFormattingRule; }
      }
      public string DomesticCarrierCodeFormattingRule {
        get { return result.DomesticCarrierCodeFormattingRule; }
        set { SetDomesticCarrierCodeFormattingRule(value); }
      }
      public Builder SetDomesticCarrierCodeFormattingRule(string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasDomesticCarrierCodeFormattingRule = true;
        result.domesticCarrierCodeFormattingRule_ = value;
        return this;
      }
      public Builder ClearDomesticCarrierCodeFormattingRule() {
        result.hasDomesticCarrierCodeFormattingRule = false;
        result.domesticCarrierCodeFormattingRule_ = "";
        return this;
      }
    }
    static NumberFormat() {
      object.ReferenceEquals(global::PhoneNumbers.Phonemetadata.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
  public partial class PhoneNumberDesc {
    private static readonly PhoneNumberDesc defaultInstance = new Builder().BuildPartial();
    public static PhoneNumberDesc DefaultInstance {
      get { return defaultInstance; }
    }
    
    public PhoneNumberDesc DefaultInstanceForType {
      get { return defaultInstance; }
    }
    
    protected PhoneNumberDesc ThisMessage {
      get { return this; }
    }
    
    public const int NationalNumberPatternFieldNumber = 2;
    private bool hasNationalNumberPattern;
    private string nationalNumberPattern_ = "";
    public bool HasNationalNumberPattern {
      get { return hasNationalNumberPattern; }
    }
    public string NationalNumberPattern {
      get { return nationalNumberPattern_; }
    }
    
    public const int PossibleLengthFieldNumber = 9;
    private scg::List<int> possibleLength_ = new scg::List<int>();
    public scg::IList<int> PossibleLengthList {
      get { return possibleLength_; }
    }
    public int PossibleLengthCount {
      get { return possibleLength_.Count; }
    }
    public int GetPossibleLength(int index) {
      return possibleLength_[index];
    }
    
    public const int PossibleLengthLocalOnlyFieldNumber = 10;
    private scg::List<int> possibleLengthLocalOnly_ = new scg::List<int>();
    public scg::IList<int> PossibleLengthLocalOnlyList {
      get { return possibleLengthLocalOnly_; }
    }
    public int PossibleLengthLocalOnlyCount {
      get { return possibleLengthLocalOnly_.Count; }
    }
    public int GetPossibleLengthLocalOnly(int index) {
      return possibleLengthLocalOnly_[index];
    }
    
    public const int ExampleNumberFieldNumber = 6;
    private bool hasExampleNumber;
    private string exampleNumber_ = "";
    public bool HasExampleNumber {
      get { return hasExampleNumber; }
    }
    public string ExampleNumber {
      get { return exampleNumber_; }
    }
    
    public bool IsInitialized {
      get {
        return true;
      }
    }
    
    
    
    
    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      if (hasNationalNumberPattern) hash ^= nationalNumberPattern_.GetHashCode();
      foreach(int i in possibleLength_)
        hash ^= i.GetHashCode();
      foreach(int i in possibleLengthLocalOnly_)
        hash ^= i.GetHashCode();
      if (hasExampleNumber) hash ^= exampleNumber_.GetHashCode();
      return hash;
    }
    
    public override bool Equals(object obj) {
      PhoneNumberDesc other = obj as PhoneNumberDesc;
      if (other == null) return false;
      if (hasNationalNumberPattern != other.hasNationalNumberPattern || (hasNationalNumberPattern && !nationalNumberPattern_.Equals(other.nationalNumberPattern_))) return false;
      if(possibleLength_.Count != other.possibleLength_.Count) return false;
      for(int ix=0; ix < possibleLength_.Count; ix++)
        if(!possibleLength_[ix].Equals(other.possibleLength_[ix])) return false;
      if(possibleLengthLocalOnly_.Count != other.possibleLengthLocalOnly_.Count) return false;
      for(int ix=0; ix < possibleLengthLocalOnly_.Count; ix++)
        if(!possibleLengthLocalOnly_[ix].Equals(other.possibleLengthLocalOnly_[ix])) return false;
      if (hasExampleNumber != other.hasExampleNumber || (hasExampleNumber && !exampleNumber_.Equals(other.exampleNumber_))) return false;
      return true;
    }
    
    #endregion
    
    public static Builder CreateBuilder() { return new Builder(); }
    public Builder ToBuilder() { return CreateBuilder(this); }
    public Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(PhoneNumberDesc prototype) {
      return (Builder) new Builder().MergeFrom(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public partial class Builder {
      protected Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {}
      
      PhoneNumberDesc result = new PhoneNumberDesc();
      
      protected PhoneNumberDesc MessageBeingBuilt {
        get { return result; }
      }
      
      public Builder Clear() {
        result = new PhoneNumberDesc();
        return this;
      }
      
      public Builder Clone() {
        return new Builder().MergeFrom(result);
      }
      
      public PhoneNumberDesc DefaultInstanceForType {
        get { return global::PhoneNumbers.PhoneNumberDesc.DefaultInstance; }
      }
      
      public PhoneNumberDesc Build() { return BuildPartial(); }
      
      public PhoneNumberDesc BuildPartial() {
        if (result == null) {
          throw new global::System.InvalidOperationException("build() has already been called on this Builder");
        }


        PhoneNumberDesc returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      public Builder MergeFrom(PhoneNumberDesc other) {
        if (other == global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) return this;
        if (other.HasNationalNumberPattern) {
          NationalNumberPattern = other.NationalNumberPattern;
        }
        if (other.possibleLength_.Count != 0) {
           result.possibleLength_.AddRange(other.possibleLength_);
        }
        if (other.possibleLengthLocalOnly_.Count != 0) {
           result.possibleLengthLocalOnly_.AddRange(other.possibleLengthLocalOnly_);
        }
        if (other.HasExampleNumber) {
          ExampleNumber = other.ExampleNumber;
        }
        return this;
      }
      
      
      
      
      public bool HasNationalNumberPattern {
        get { return result.HasNationalNumberPattern; }
      }
      public string NationalNumberPattern {
        get { return result.NationalNumberPattern; }
        set { SetNationalNumberPattern(value); }
      }
      public Builder SetNationalNumberPattern(string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasNationalNumberPattern = true;
        result.nationalNumberPattern_ = value;
        return this;
      }
      public Builder ClearNationalNumberPattern() {
        result.hasNationalNumberPattern = false;
        result.nationalNumberPattern_ = "";
        return this;
      }
      
      public scg::IList<int> PossibleLengthList {
        get { return result.possibleLength_; }
      }
      public int PossibleLengthCount {
        get { return result.PossibleLengthCount; }
      }
      public int GetPossibleLength(int index) {
        return result.GetPossibleLength(index);
      }
      public Builder SetPossibleLength(int index, int value) {
        result.possibleLength_[index] = value;
        return this;
      }
      public Builder AddPossibleLength(int value) {
        result.possibleLength_.Add(value);
        return this;
      }
      public Builder AddRangePossibleLength(scg::IEnumerable<int> values) {
         result.possibleLength_.AddRange(values);
        return this;
      }
      public Builder ClearPossibleLength() {
        result.possibleLength_.Clear();
        return this;
      }
      
      public scg::IList<int> PossibleLengthLocalOnlyList {
        get { return result.possibleLengthLocalOnly_; }
      }
      public int PossibleLengthLocalOnlyCount {
        get { return result.PossibleLengthLocalOnlyCount; }
      }
      public int GetPossibleLengthLocalOnly(int index) {
        return result.GetPossibleLengthLocalOnly(index);
      }
      public Builder SetPossibleLengthLocalOnly(int index, int value) {
        result.possibleLengthLocalOnly_[index] = value;
        return this;
      }
      public Builder AddPossibleLengthLocalOnly(int value) {
        result.possibleLengthLocalOnly_.Add(value);
        return this;
      }
      public Builder AddRangePossibleLengthLocalOnly(scg::IEnumerable<int> values) {
         result.possibleLengthLocalOnly_.AddRange(values);
        return this;
      }
      public Builder ClearPossibleLengthLocalOnly() {
        result.possibleLengthLocalOnly_.Clear();
        return this;
      }
      
      public bool HasExampleNumber {
        get { return result.HasExampleNumber; }
      }
      public string ExampleNumber {
        get { return result.ExampleNumber; }
        set { SetExampleNumber(value); }
      }
      public Builder SetExampleNumber(string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasExampleNumber = true;
        result.exampleNumber_ = value;
        return this;
      }
      public Builder ClearExampleNumber() {
        result.hasExampleNumber = false;
        result.exampleNumber_ = "";
        return this;
      }
    }
    static PhoneNumberDesc() {
      object.ReferenceEquals(global::PhoneNumbers.Phonemetadata.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
  public partial class PhoneMetadata {
    private static readonly PhoneMetadata defaultInstance = new Builder().BuildPartial();
    public static PhoneMetadata DefaultInstance {
      get { return defaultInstance; }
    }
    
    public PhoneMetadata DefaultInstanceForType {
      get { return defaultInstance; }
    }
    
    protected PhoneMetadata ThisMessage {
      get { return this; }
    }
    
    public const int GeneralDescFieldNumber = 1;
    private bool hasGeneralDesc;
    private global::PhoneNumbers.PhoneNumberDesc generalDesc_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasGeneralDesc {
      get { return hasGeneralDesc; }
    }
    public global::PhoneNumbers.PhoneNumberDesc GeneralDesc {
      get { return generalDesc_; }
    }
    
    public const int FixedLineFieldNumber = 2;
    private bool hasFixedLine;
    private global::PhoneNumbers.PhoneNumberDesc fixedLine_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasFixedLine {
      get { return hasFixedLine; }
    }
    public global::PhoneNumbers.PhoneNumberDesc FixedLine {
      get { return fixedLine_; }
    }
    
    public const int MobileFieldNumber = 3;
    private bool hasMobile;
    private global::PhoneNumbers.PhoneNumberDesc mobile_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasMobile {
      get { return hasMobile; }
    }
    public global::PhoneNumbers.PhoneNumberDesc Mobile {
      get { return mobile_; }
    }
    
    public const int TollFreeFieldNumber = 4;
    private bool hasTollFree;
    private global::PhoneNumbers.PhoneNumberDesc tollFree_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasTollFree {
      get { return hasTollFree; }
    }
    public global::PhoneNumbers.PhoneNumberDesc TollFree {
      get { return tollFree_; }
    }
    
    public const int PremiumRateFieldNumber = 5;
    private bool hasPremiumRate;
    private global::PhoneNumbers.PhoneNumberDesc premiumRate_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasPremiumRate {
      get { return hasPremiumRate; }
    }
    public global::PhoneNumbers.PhoneNumberDesc PremiumRate {
      get { return premiumRate_; }
    }
    
    public const int SharedCostFieldNumber = 6;
    private bool hasSharedCost;
    private global::PhoneNumbers.PhoneNumberDesc sharedCost_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasSharedCost {
      get { return hasSharedCost; }
    }
    public global::PhoneNumbers.PhoneNumberDesc SharedCost {
      get { return sharedCost_; }
    }
    
    public const int PersonalNumberFieldNumber = 7;
    private bool hasPersonalNumber;
    private global::PhoneNumbers.PhoneNumberDesc personalNumber_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasPersonalNumber {
      get { return hasPersonalNumber; }
    }
    public global::PhoneNumbers.PhoneNumberDesc PersonalNumber {
      get { return personalNumber_; }
    }
    
    public const int VoipFieldNumber = 8;
    private bool hasVoip;
    private global::PhoneNumbers.PhoneNumberDesc voip_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasVoip {
      get { return hasVoip; }
    }
    public global::PhoneNumbers.PhoneNumberDesc Voip {
      get { return voip_; }
    }
    
    public const int PagerFieldNumber = 21;
    private bool hasPager;
    private global::PhoneNumbers.PhoneNumberDesc pager_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasPager {
      get { return hasPager; }
    }
    public global::PhoneNumbers.PhoneNumberDesc Pager {
      get { return pager_; }
    }
    
    public const int UanFieldNumber = 25;
    private bool hasUan;
    private global::PhoneNumbers.PhoneNumberDesc uan_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasUan {
      get { return hasUan; }
    }
    public global::PhoneNumbers.PhoneNumberDesc Uan {
      get { return uan_; }
    }
    
    public const int EmergencyFieldNumber = 27;
    private bool hasEmergency;
    private global::PhoneNumbers.PhoneNumberDesc emergency_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasEmergency {
      get { return hasEmergency; }
    }
    public global::PhoneNumbers.PhoneNumberDesc Emergency {
      get { return emergency_; }
    }
    
    public const int VoicemailFieldNumber = 28;
    private bool hasVoicemail;
    private global::PhoneNumbers.PhoneNumberDesc voicemail_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasVoicemail {
      get { return hasVoicemail; }
    }
    public global::PhoneNumbers.PhoneNumberDesc Voicemail {
      get { return voicemail_; }
    }
    
    public const int ShortCodeFieldNumber = 29;
    private bool hasShortCode;
    private global::PhoneNumbers.PhoneNumberDesc shortCode_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasShortCode {
      get { return hasShortCode; }
    }
    public global::PhoneNumbers.PhoneNumberDesc ShortCode {
      get { return shortCode_; }
    }
    
    public const int StandardRateFieldNumber = 30;
    private bool hasStandardRate;
    private global::PhoneNumbers.PhoneNumberDesc standardRate_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasStandardRate {
      get { return hasStandardRate; }
    }
    public global::PhoneNumbers.PhoneNumberDesc StandardRate {
      get { return standardRate_; }
    }
    
    public const int CarrierSpecificFieldNumber = 31;
    private bool hasCarrierSpecific;
    private global::PhoneNumbers.PhoneNumberDesc carrierSpecific_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasCarrierSpecific {
      get { return hasCarrierSpecific; }
    }
    public global::PhoneNumbers.PhoneNumberDesc CarrierSpecific {
      get { return carrierSpecific_; }
    }
    
    public const int SmsServicesFieldNumber = 33;
    private bool hasSmsServices;
    private global::PhoneNumbers.PhoneNumberDesc smsServices_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasSmsServices {
      get { return hasSmsServices; }
    }
    public global::PhoneNumbers.PhoneNumberDesc SmsServices {
      get { return smsServices_; }
    }
    
    public const int NoInternationalDiallingFieldNumber = 24;
    private bool hasNoInternationalDialling;
    private global::PhoneNumbers.PhoneNumberDesc noInternationalDialling_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
    public bool HasNoInternationalDialling {
      get { return hasNoInternationalDialling; }
    }
    public global::PhoneNumbers.PhoneNumberDesc NoInternationalDialling {
      get { return noInternationalDialling_; }
    }
    
    public const int IdFieldNumber = 9;
    private bool hasId;
    private string id_ = "";
    public bool HasId {
      get { return hasId; }
    }
    public string Id {
      get { return id_; }
    }
    
    public const int CountryCodeFieldNumber = 10;
    private bool hasCountryCode;
    private int countryCode_ = 0;
    public bool HasCountryCode {
      get { return hasCountryCode; }
    }
    public int CountryCode {
      get { return countryCode_; }
    }
    
    public const int InternationalPrefixFieldNumber = 11;
    private bool hasInternationalPrefix;
    private string internationalPrefix_ = "";
    public bool HasInternationalPrefix {
      get { return hasInternationalPrefix; }
    }
    public string InternationalPrefix {
      get { return internationalPrefix_; }
    }
    
    public const int PreferredInternationalPrefixFieldNumber = 17;
    private bool hasPreferredInternationalPrefix;
    private string preferredInternationalPrefix_ = "";
    public bool HasPreferredInternationalPrefix {
      get { return hasPreferredInternationalPrefix; }
    }
    public string PreferredInternationalPrefix {
      get { return preferredInternationalPrefix_; }
    }
    
    public const int NationalPrefixFieldNumber = 12;
    private bool hasNationalPrefix;
    private string nationalPrefix_ = "";
    public bool HasNationalPrefix {
      get { return hasNationalPrefix; }
    }
    public string NationalPrefix {
      get { return nationalPrefix_; }
    }
    
    public const int PreferredExtnPrefixFieldNumber = 13;
    private bool hasPreferredExtnPrefix;
    private string preferredExtnPrefix_ = "";
    public bool HasPreferredExtnPrefix {
      get { return hasPreferredExtnPrefix; }
    }
    public string PreferredExtnPrefix {
      get { return preferredExtnPrefix_; }
    }
    
    public const int NationalPrefixForParsingFieldNumber = 15;
    private bool hasNationalPrefixForParsing;
    private string nationalPrefixForParsing_ = "";
    public bool HasNationalPrefixForParsing {
      get { return hasNationalPrefixForParsing; }
    }
    public string NationalPrefixForParsing {
      get { return nationalPrefixForParsing_; }
    }
    
    public const int NationalPrefixTransformRuleFieldNumber = 16;
    private bool hasNationalPrefixTransformRule;
    private string nationalPrefixTransformRule_ = "";
    public bool HasNationalPrefixTransformRule {
      get { return hasNationalPrefixTransformRule; }
    }
    public string NationalPrefixTransformRule {
      get { return nationalPrefixTransformRule_; }
    }
    
    public const int SameMobileAndFixedLinePatternFieldNumber = 18;
    private bool hasSameMobileAndFixedLinePattern;
    private bool sameMobileAndFixedLinePattern_ = false;
    public bool HasSameMobileAndFixedLinePattern {
      get { return hasSameMobileAndFixedLinePattern; }
    }
    public bool SameMobileAndFixedLinePattern {
      get { return sameMobileAndFixedLinePattern_; }
    }
    
    public const int NumberFormatFieldNumber = 19;
    private scg::List<global::PhoneNumbers.NumberFormat> numberFormat_ = new scg::List<global::PhoneNumbers.NumberFormat>();
    public scg::IList<global::PhoneNumbers.NumberFormat> NumberFormatList {
      get { return numberFormat_; }
    }
    public int NumberFormatCount {
      get { return numberFormat_.Count; }
    }
    public global::PhoneNumbers.NumberFormat GetNumberFormat(int index) {
      return numberFormat_[index];
    }
    
    public const int IntlNumberFormatFieldNumber = 20;
    private scg::List<global::PhoneNumbers.NumberFormat> intlNumberFormat_ = new scg::List<global::PhoneNumbers.NumberFormat>();
    public scg::IList<global::PhoneNumbers.NumberFormat> IntlNumberFormatList {
      get { return intlNumberFormat_; }
    }
    public int IntlNumberFormatCount {
      get { return intlNumberFormat_.Count; }
    }
    public global::PhoneNumbers.NumberFormat GetIntlNumberFormat(int index) {
      return intlNumberFormat_[index];
    }
    
    public const int MainCountryForCodeFieldNumber = 22;
    private bool hasMainCountryForCode;
    private bool mainCountryForCode_ = false;
    public bool HasMainCountryForCode {
      get { return hasMainCountryForCode; }
    }
    public bool MainCountryForCode {
      get { return mainCountryForCode_; }
    }
    
    public const int LeadingDigitsFieldNumber = 23;
    private bool hasLeadingDigits;
    private string leadingDigits_ = "";
    public bool HasLeadingDigits {
      get { return hasLeadingDigits; }
    }
    public string LeadingDigits {
      get { return leadingDigits_; }
    }
    
    public const int LeadingZeroPossibleFieldNumber = 26;
    private bool hasLeadingZeroPossible;
    private bool leadingZeroPossible_ = false;
    public bool HasLeadingZeroPossible {
      get { return hasLeadingZeroPossible; }
    }
    public bool LeadingZeroPossible {
      get { return leadingZeroPossible_; }
    }
    
    public const int MobileNumberPortableRegionFieldNumber = 32;
    private bool hasMobileNumberPortableRegion;
    private bool mobileNumberPortableRegion_ = false;
    public bool HasMobileNumberPortableRegion {
      get { return hasMobileNumberPortableRegion; }
    }
    public bool MobileNumberPortableRegion {
      get { return mobileNumberPortableRegion_; }
    }
    
    public bool IsInitialized {
      get {
        if (!hasId) return false;
        foreach (global::PhoneNumbers.NumberFormat element in NumberFormatList) {
          if (!element.IsInitialized) return false;
        }
        foreach (global::PhoneNumbers.NumberFormat element in IntlNumberFormatList) {
          if (!element.IsInitialized) return false;
        }
        return true;
      }
    }
    
    
    
    
    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      if (hasGeneralDesc) hash ^= generalDesc_.GetHashCode();
      if (hasFixedLine) hash ^= fixedLine_.GetHashCode();
      if (hasMobile) hash ^= mobile_.GetHashCode();
      if (hasTollFree) hash ^= tollFree_.GetHashCode();
      if (hasPremiumRate) hash ^= premiumRate_.GetHashCode();
      if (hasSharedCost) hash ^= sharedCost_.GetHashCode();
      if (hasPersonalNumber) hash ^= personalNumber_.GetHashCode();
      if (hasVoip) hash ^= voip_.GetHashCode();
      if (hasPager) hash ^= pager_.GetHashCode();
      if (hasUan) hash ^= uan_.GetHashCode();
      if (hasEmergency) hash ^= emergency_.GetHashCode();
      if (hasVoicemail) hash ^= voicemail_.GetHashCode();
      if (hasShortCode) hash ^= shortCode_.GetHashCode();
      if (hasStandardRate) hash ^= standardRate_.GetHashCode();
      if (hasCarrierSpecific) hash ^= carrierSpecific_.GetHashCode();
      if (hasSmsServices) hash ^= smsServices_.GetHashCode();
      if (hasNoInternationalDialling) hash ^= noInternationalDialling_.GetHashCode();
      if (hasId) hash ^= id_.GetHashCode();
      if (hasCountryCode) hash ^= countryCode_.GetHashCode();
      if (hasInternationalPrefix) hash ^= internationalPrefix_.GetHashCode();
      if (hasPreferredInternationalPrefix) hash ^= preferredInternationalPrefix_.GetHashCode();
      if (hasNationalPrefix) hash ^= nationalPrefix_.GetHashCode();
      if (hasPreferredExtnPrefix) hash ^= preferredExtnPrefix_.GetHashCode();
      if (hasNationalPrefixForParsing) hash ^= nationalPrefixForParsing_.GetHashCode();
      if (hasNationalPrefixTransformRule) hash ^= nationalPrefixTransformRule_.GetHashCode();
      if (hasSameMobileAndFixedLinePattern) hash ^= sameMobileAndFixedLinePattern_.GetHashCode();
      foreach(global::PhoneNumbers.NumberFormat i in numberFormat_)
        hash ^= i.GetHashCode();
      foreach(global::PhoneNumbers.NumberFormat i in intlNumberFormat_)
        hash ^= i.GetHashCode();
      if (hasMainCountryForCode) hash ^= mainCountryForCode_.GetHashCode();
      if (hasLeadingDigits) hash ^= leadingDigits_.GetHashCode();
      if (hasLeadingZeroPossible) hash ^= leadingZeroPossible_.GetHashCode();
      if (hasMobileNumberPortableRegion) hash ^= mobileNumberPortableRegion_.GetHashCode();
      return hash;
    }
    
    public override bool Equals(object obj) {
      PhoneMetadata other = obj as PhoneMetadata;
      if (other == null) return false;
      if (hasGeneralDesc != other.hasGeneralDesc || (hasGeneralDesc && !generalDesc_.Equals(other.generalDesc_))) return false;
      if (hasFixedLine != other.hasFixedLine || (hasFixedLine && !fixedLine_.Equals(other.fixedLine_))) return false;
      if (hasMobile != other.hasMobile || (hasMobile && !mobile_.Equals(other.mobile_))) return false;
      if (hasTollFree != other.hasTollFree || (hasTollFree && !tollFree_.Equals(other.tollFree_))) return false;
      if (hasPremiumRate != other.hasPremiumRate || (hasPremiumRate && !premiumRate_.Equals(other.premiumRate_))) return false;
      if (hasSharedCost != other.hasSharedCost || (hasSharedCost && !sharedCost_.Equals(other.sharedCost_))) return false;
      if (hasPersonalNumber != other.hasPersonalNumber || (hasPersonalNumber && !personalNumber_.Equals(other.personalNumber_))) return false;
      if (hasVoip != other.hasVoip || (hasVoip && !voip_.Equals(other.voip_))) return false;
      if (hasPager != other.hasPager || (hasPager && !pager_.Equals(other.pager_))) return false;
      if (hasUan != other.hasUan || (hasUan && !uan_.Equals(other.uan_))) return false;
      if (hasEmergency != other.hasEmergency || (hasEmergency && !emergency_.Equals(other.emergency_))) return false;
      if (hasVoicemail != other.hasVoicemail || (hasVoicemail && !voicemail_.Equals(other.voicemail_))) return false;
      if (hasShortCode != other.hasShortCode || (hasShortCode && !shortCode_.Equals(other.shortCode_))) return false;
      if (hasStandardRate != other.hasStandardRate || (hasStandardRate && !standardRate_.Equals(other.standardRate_))) return false;
      if (hasCarrierSpecific != other.hasCarrierSpecific || (hasCarrierSpecific && !carrierSpecific_.Equals(other.carrierSpecific_))) return false;
      if (hasSmsServices != other.hasSmsServices || (hasSmsServices && !smsServices_.Equals(other.smsServices_))) return false;
      if (hasNoInternationalDialling != other.hasNoInternationalDialling || (hasNoInternationalDialling && !noInternationalDialling_.Equals(other.noInternationalDialling_))) return false;
      if (hasId != other.hasId || (hasId && !id_.Equals(other.id_))) return false;
      if (hasCountryCode != other.hasCountryCode || (hasCountryCode && !countryCode_.Equals(other.countryCode_))) return false;
      if (hasInternationalPrefix != other.hasInternationalPrefix || (hasInternationalPrefix && !internationalPrefix_.Equals(other.internationalPrefix_))) return false;
      if (hasPreferredInternationalPrefix != other.hasPreferredInternationalPrefix || (hasPreferredInternationalPrefix && !preferredInternationalPrefix_.Equals(other.preferredInternationalPrefix_))) return false;
      if (hasNationalPrefix != other.hasNationalPrefix || (hasNationalPrefix && !nationalPrefix_.Equals(other.nationalPrefix_))) return false;
      if (hasPreferredExtnPrefix != other.hasPreferredExtnPrefix || (hasPreferredExtnPrefix && !preferredExtnPrefix_.Equals(other.preferredExtnPrefix_))) return false;
      if (hasNationalPrefixForParsing != other.hasNationalPrefixForParsing || (hasNationalPrefixForParsing && !nationalPrefixForParsing_.Equals(other.nationalPrefixForParsing_))) return false;
      if (hasNationalPrefixTransformRule != other.hasNationalPrefixTransformRule || (hasNationalPrefixTransformRule && !nationalPrefixTransformRule_.Equals(other.nationalPrefixTransformRule_))) return false;
      if (hasSameMobileAndFixedLinePattern != other.hasSameMobileAndFixedLinePattern || (hasSameMobileAndFixedLinePattern && !sameMobileAndFixedLinePattern_.Equals(other.sameMobileAndFixedLinePattern_))) return false;
      if(numberFormat_.Count != other.numberFormat_.Count) return false;
      for(int ix=0; ix < numberFormat_.Count; ix++)
        if(!numberFormat_[ix].Equals(other.numberFormat_[ix])) return false;
      if(intlNumberFormat_.Count != other.intlNumberFormat_.Count) return false;
      for(int ix=0; ix < intlNumberFormat_.Count; ix++)
        if(!intlNumberFormat_[ix].Equals(other.intlNumberFormat_[ix])) return false;
      if (hasMainCountryForCode != other.hasMainCountryForCode || (hasMainCountryForCode && !mainCountryForCode_.Equals(other.mainCountryForCode_))) return false;
      if (hasLeadingDigits != other.hasLeadingDigits || (hasLeadingDigits && !leadingDigits_.Equals(other.leadingDigits_))) return false;
      if (hasLeadingZeroPossible != other.hasLeadingZeroPossible || (hasLeadingZeroPossible && !leadingZeroPossible_.Equals(other.leadingZeroPossible_))) return false;
      if (hasMobileNumberPortableRegion != other.hasMobileNumberPortableRegion || (hasMobileNumberPortableRegion && !mobileNumberPortableRegion_.Equals(other.mobileNumberPortableRegion_))) return false;
      return true;
    }
    
    #endregion
    
    public static Builder CreateBuilder() { return new Builder(); }
    public Builder ToBuilder() { return CreateBuilder(this); }
    public Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(PhoneMetadata prototype) {
      return (Builder) new Builder().MergeFrom(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public partial class Builder {
      protected Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {}
      
      PhoneMetadata result = new PhoneMetadata();
      
      protected PhoneMetadata MessageBeingBuilt {
        get { return result; }
      }
      
      public Builder Clear() {
        result = new PhoneMetadata();
        return this;
      }
      
      public Builder Clone() {
        return new Builder().MergeFrom(result);
      }
      
      public PhoneMetadata DefaultInstanceForType {
        get { return global::PhoneNumbers.PhoneMetadata.DefaultInstance; }
      }
      
      public PhoneMetadata Build() { return BuildPartial(); }
      
      public PhoneMetadata BuildPartial() {
        if (result == null) {
          throw new global::System.InvalidOperationException("build() has already been called on this Builder");
        }


        PhoneMetadata returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      public Builder MergeFrom(PhoneMetadata other) {
        if (other == global::PhoneNumbers.PhoneMetadata.DefaultInstance) return this;
        if (other.HasGeneralDesc) {
          MergeGeneralDesc(other.GeneralDesc);
        }
        if (other.HasFixedLine) {
          MergeFixedLine(other.FixedLine);
        }
        if (other.HasMobile) {
          MergeMobile(other.Mobile);
        }
        if (other.HasTollFree) {
          MergeTollFree(other.TollFree);
        }
        if (other.HasPremiumRate) {
          MergePremiumRate(other.PremiumRate);
        }
        if (other.HasSharedCost) {
          MergeSharedCost(other.SharedCost);
        }
        if (other.HasPersonalNumber) {
          MergePersonalNumber(other.PersonalNumber);
        }
        if (other.HasVoip) {
          MergeVoip(other.Voip);
        }
        if (other.HasPager) {
          MergePager(other.Pager);
        }
        if (other.HasUan) {
          MergeUan(other.Uan);
        }
        if (other.HasEmergency) {
          MergeEmergency(other.Emergency);
        }
        if (other.HasVoicemail) {
          MergeVoicemail(other.Voicemail);
        }
        if (other.HasShortCode) {
          MergeShortCode(other.ShortCode);
        }
        if (other.HasStandardRate) {
          MergeStandardRate(other.StandardRate);
        }
        if (other.HasCarrierSpecific) {
          MergeCarrierSpecific(other.CarrierSpecific);
        }
        if (other.HasSmsServices) {
          MergeSmsServices(other.SmsServices);
        }
        if (other.HasNoInternationalDialling) {
          MergeNoInternationalDialling(other.NoInternationalDialling);
        }
        if (other.HasId) {
          Id = other.Id;
        }
        if (other.HasCountryCode) {
          CountryCode = other.CountryCode;
        }
        if (other.HasInternationalPrefix) {
          InternationalPrefix = other.InternationalPrefix;
        }
        if (other.HasPreferredInternationalPrefix) {
          PreferredInternationalPrefix = other.PreferredInternationalPrefix;
        }
        if (other.HasNationalPrefix) {
          NationalPrefix = other.NationalPrefix;
        }
        if (other.HasPreferredExtnPrefix) {
          PreferredExtnPrefix = other.PreferredExtnPrefix;
        }
        if (other.HasNationalPrefixForParsing) {
          NationalPrefixForParsing = other.NationalPrefixForParsing;
        }
        if (other.HasNationalPrefixTransformRule) {
          NationalPrefixTransformRule = other.NationalPrefixTransformRule;
        }
        if (other.HasSameMobileAndFixedLinePattern) {
          SameMobileAndFixedLinePattern = other.SameMobileAndFixedLinePattern;
        }
        if (other.numberFormat_.Count != 0) {
           result.numberFormat_.AddRange(other.numberFormat_);
        }
        if (other.intlNumberFormat_.Count != 0) {
           result.intlNumberFormat_.AddRange(other.intlNumberFormat_);
        }
        if (other.HasMainCountryForCode) {
          MainCountryForCode = other.MainCountryForCode;
        }
        if (other.HasLeadingDigits) {
          LeadingDigits = other.LeadingDigits;
        }
        if (other.HasLeadingZeroPossible) {
          LeadingZeroPossible = other.LeadingZeroPossible;
        }
        if (other.HasMobileNumberPortableRegion) {
          MobileNumberPortableRegion = other.MobileNumberPortableRegion;
        }
        return this;
      }
      
      
      
      
      public bool HasGeneralDesc {
       get { return result.HasGeneralDesc; }
      }
      public global::PhoneNumbers.PhoneNumberDesc GeneralDesc {
        get { return result.GeneralDesc; }
        set { SetGeneralDesc(value); }
      }
      public Builder SetGeneralDesc(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasGeneralDesc = true;
        result.generalDesc_ = value;
        return this;
      }
      public Builder SetGeneralDesc(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasGeneralDesc = true;
        result.generalDesc_ = builderForValue.Build();
        return this;
      }
      public Builder MergeGeneralDesc(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasGeneralDesc &&
            result.generalDesc_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.generalDesc_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.generalDesc_).MergeFrom(value).BuildPartial();
        } else {
          result.generalDesc_ = value;
        }
        result.hasGeneralDesc = true;
        return this;
      }
      public Builder ClearGeneralDesc() {
        result.hasGeneralDesc = false;
        result.generalDesc_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasFixedLine {
       get { return result.HasFixedLine; }
      }
      public global::PhoneNumbers.PhoneNumberDesc FixedLine {
        get { return result.FixedLine; }
        set { SetFixedLine(value); }
      }
      public Builder SetFixedLine(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasFixedLine = true;
        result.fixedLine_ = value;
        return this;
      }
      public Builder SetFixedLine(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasFixedLine = true;
        result.fixedLine_ = builderForValue.Build();
        return this;
      }
      public Builder MergeFixedLine(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasFixedLine &&
            result.fixedLine_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.fixedLine_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.fixedLine_).MergeFrom(value).BuildPartial();
        } else {
          result.fixedLine_ = value;
        }
        result.hasFixedLine = true;
        return this;
      }
      public Builder ClearFixedLine() {
        result.hasFixedLine = false;
        result.fixedLine_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasMobile {
       get { return result.HasMobile; }
      }
      public global::PhoneNumbers.PhoneNumberDesc Mobile {
        get { return result.Mobile; }
        set { SetMobile(value); }
      }
      public Builder SetMobile(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasMobile = true;
        result.mobile_ = value;
        return this;
      }
      public Builder SetMobile(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasMobile = true;
        result.mobile_ = builderForValue.Build();
        return this;
      }
      public Builder MergeMobile(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasMobile &&
            result.mobile_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.mobile_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.mobile_).MergeFrom(value).BuildPartial();
        } else {
          result.mobile_ = value;
        }
        result.hasMobile = true;
        return this;
      }
      public Builder ClearMobile() {
        result.hasMobile = false;
        result.mobile_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasTollFree {
       get { return result.HasTollFree; }
      }
      public global::PhoneNumbers.PhoneNumberDesc TollFree {
        get { return result.TollFree; }
        set { SetTollFree(value); }
      }
      public Builder SetTollFree(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasTollFree = true;
        result.tollFree_ = value;
        return this;
      }
      public Builder SetTollFree(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasTollFree = true;
        result.tollFree_ = builderForValue.Build();
        return this;
      }
      public Builder MergeTollFree(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasTollFree &&
            result.tollFree_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.tollFree_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.tollFree_).MergeFrom(value).BuildPartial();
        } else {
          result.tollFree_ = value;
        }
        result.hasTollFree = true;
        return this;
      }
      public Builder ClearTollFree() {
        result.hasTollFree = false;
        result.tollFree_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasPremiumRate {
       get { return result.HasPremiumRate; }
      }
      public global::PhoneNumbers.PhoneNumberDesc PremiumRate {
        get { return result.PremiumRate; }
        set { SetPremiumRate(value); }
      }
      public Builder SetPremiumRate(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasPremiumRate = true;
        result.premiumRate_ = value;
        return this;
      }
      public Builder SetPremiumRate(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasPremiumRate = true;
        result.premiumRate_ = builderForValue.Build();
        return this;
      }
      public Builder MergePremiumRate(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasPremiumRate &&
            result.premiumRate_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.premiumRate_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.premiumRate_).MergeFrom(value).BuildPartial();
        } else {
          result.premiumRate_ = value;
        }
        result.hasPremiumRate = true;
        return this;
      }
      public Builder ClearPremiumRate() {
        result.hasPremiumRate = false;
        result.premiumRate_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasSharedCost {
       get { return result.HasSharedCost; }
      }
      public global::PhoneNumbers.PhoneNumberDesc SharedCost {
        get { return result.SharedCost; }
        set { SetSharedCost(value); }
      }
      public Builder SetSharedCost(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasSharedCost = true;
        result.sharedCost_ = value;
        return this;
      }
      public Builder SetSharedCost(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasSharedCost = true;
        result.sharedCost_ = builderForValue.Build();
        return this;
      }
      public Builder MergeSharedCost(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasSharedCost &&
            result.sharedCost_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.sharedCost_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.sharedCost_).MergeFrom(value).BuildPartial();
        } else {
          result.sharedCost_ = value;
        }
        result.hasSharedCost = true;
        return this;
      }
      public Builder ClearSharedCost() {
        result.hasSharedCost = false;
        result.sharedCost_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasPersonalNumber {
       get { return result.HasPersonalNumber; }
      }
      public global::PhoneNumbers.PhoneNumberDesc PersonalNumber {
        get { return result.PersonalNumber; }
        set { SetPersonalNumber(value); }
      }
      public Builder SetPersonalNumber(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasPersonalNumber = true;
        result.personalNumber_ = value;
        return this;
      }
      public Builder SetPersonalNumber(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasPersonalNumber = true;
        result.personalNumber_ = builderForValue.Build();
        return this;
      }
      public Builder MergePersonalNumber(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasPersonalNumber &&
            result.personalNumber_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.personalNumber_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.personalNumber_).MergeFrom(value).BuildPartial();
        } else {
          result.personalNumber_ = value;
        }
        result.hasPersonalNumber = true;
        return this;
      }
      public Builder ClearPersonalNumber() {
        result.hasPersonalNumber = false;
        result.personalNumber_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasVoip {
       get { return result.HasVoip; }
      }
      public global::PhoneNumbers.PhoneNumberDesc Voip {
        get { return result.Voip; }
        set { SetVoip(value); }
      }
      public Builder SetVoip(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasVoip = true;
        result.voip_ = value;
        return this;
      }
      public Builder SetVoip(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasVoip = true;
        result.voip_ = builderForValue.Build();
        return this;
      }
      public Builder MergeVoip(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasVoip &&
            result.voip_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.voip_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.voip_).MergeFrom(value).BuildPartial();
        } else {
          result.voip_ = value;
        }
        result.hasVoip = true;
        return this;
      }
      public Builder ClearVoip() {
        result.hasVoip = false;
        result.voip_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasPager {
       get { return result.HasPager; }
      }
      public global::PhoneNumbers.PhoneNumberDesc Pager {
        get { return result.Pager; }
        set { SetPager(value); }
      }
      public Builder SetPager(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasPager = true;
        result.pager_ = value;
        return this;
      }
      public Builder SetPager(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasPager = true;
        result.pager_ = builderForValue.Build();
        return this;
      }
      public Builder MergePager(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasPager &&
            result.pager_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.pager_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.pager_).MergeFrom(value).BuildPartial();
        } else {
          result.pager_ = value;
        }
        result.hasPager = true;
        return this;
      }
      public Builder ClearPager() {
        result.hasPager = false;
        result.pager_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasUan {
       get { return result.HasUan; }
      }
      public global::PhoneNumbers.PhoneNumberDesc Uan {
        get { return result.Uan; }
        set { SetUan(value); }
      }
      public Builder SetUan(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasUan = true;
        result.uan_ = value;
        return this;
      }
      public Builder SetUan(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasUan = true;
        result.uan_ = builderForValue.Build();
        return this;
      }
      public Builder MergeUan(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasUan &&
            result.uan_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.uan_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.uan_).MergeFrom(value).BuildPartial();
        } else {
          result.uan_ = value;
        }
        result.hasUan = true;
        return this;
      }
      public Builder ClearUan() {
        result.hasUan = false;
        result.uan_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasEmergency {
       get { return result.HasEmergency; }
      }
      public global::PhoneNumbers.PhoneNumberDesc Emergency {
        get { return result.Emergency; }
        set { SetEmergency(value); }
      }
      public Builder SetEmergency(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasEmergency = true;
        result.emergency_ = value;
        return this;
      }
      public Builder SetEmergency(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasEmergency = true;
        result.emergency_ = builderForValue.Build();
        return this;
      }
      public Builder MergeEmergency(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasEmergency &&
            result.emergency_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.emergency_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.emergency_).MergeFrom(value).BuildPartial();
        } else {
          result.emergency_ = value;
        }
        result.hasEmergency = true;
        return this;
      }
      public Builder ClearEmergency() {
        result.hasEmergency = false;
        result.emergency_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasVoicemail {
       get { return result.HasVoicemail; }
      }
      public global::PhoneNumbers.PhoneNumberDesc Voicemail {
        get { return result.Voicemail; }
        set { SetVoicemail(value); }
      }
      public Builder SetVoicemail(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasVoicemail = true;
        result.voicemail_ = value;
        return this;
      }
      public Builder SetVoicemail(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasVoicemail = true;
        result.voicemail_ = builderForValue.Build();
        return this;
      }
      public Builder MergeVoicemail(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasVoicemail &&
            result.voicemail_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.voicemail_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.voicemail_).MergeFrom(value).BuildPartial();
        } else {
          result.voicemail_ = value;
        }
        result.hasVoicemail = true;
        return this;
      }
      public Builder ClearVoicemail() {
        result.hasVoicemail = false;
        result.voicemail_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasShortCode {
       get { return result.HasShortCode; }
      }
      public global::PhoneNumbers.PhoneNumberDesc ShortCode {
        get { return result.ShortCode; }
        set { SetShortCode(value); }
      }
      public Builder SetShortCode(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasShortCode = true;
        result.shortCode_ = value;
        return this;
      }
      public Builder SetShortCode(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasShortCode = true;
        result.shortCode_ = builderForValue.Build();
        return this;
      }
      public Builder MergeShortCode(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasShortCode &&
            result.shortCode_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.shortCode_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.shortCode_).MergeFrom(value).BuildPartial();
        } else {
          result.shortCode_ = value;
        }
        result.hasShortCode = true;
        return this;
      }
      public Builder ClearShortCode() {
        result.hasShortCode = false;
        result.shortCode_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasStandardRate {
       get { return result.HasStandardRate; }
      }
      public global::PhoneNumbers.PhoneNumberDesc StandardRate {
        get { return result.StandardRate; }
        set { SetStandardRate(value); }
      }
      public Builder SetStandardRate(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasStandardRate = true;
        result.standardRate_ = value;
        return this;
      }
      public Builder SetStandardRate(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasStandardRate = true;
        result.standardRate_ = builderForValue.Build();
        return this;
      }
      public Builder MergeStandardRate(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasStandardRate &&
            result.standardRate_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.standardRate_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.standardRate_).MergeFrom(value).BuildPartial();
        } else {
          result.standardRate_ = value;
        }
        result.hasStandardRate = true;
        return this;
      }
      public Builder ClearStandardRate() {
        result.hasStandardRate = false;
        result.standardRate_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasCarrierSpecific {
       get { return result.HasCarrierSpecific; }
      }
      public global::PhoneNumbers.PhoneNumberDesc CarrierSpecific {
        get { return result.CarrierSpecific; }
        set { SetCarrierSpecific(value); }
      }
      public Builder SetCarrierSpecific(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasCarrierSpecific = true;
        result.carrierSpecific_ = value;
        return this;
      }
      public Builder SetCarrierSpecific(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasCarrierSpecific = true;
        result.carrierSpecific_ = builderForValue.Build();
        return this;
      }
      public Builder MergeCarrierSpecific(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasCarrierSpecific &&
            result.carrierSpecific_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.carrierSpecific_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.carrierSpecific_).MergeFrom(value).BuildPartial();
        } else {
          result.carrierSpecific_ = value;
        }
        result.hasCarrierSpecific = true;
        return this;
      }
      public Builder ClearCarrierSpecific() {
        result.hasCarrierSpecific = false;
        result.carrierSpecific_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasSmsServices {
       get { return result.HasSmsServices; }
      }
      public global::PhoneNumbers.PhoneNumberDesc SmsServices {
        get { return result.SmsServices; }
        set { SetSmsServices(value); }
      }
      public Builder SetSmsServices(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasSmsServices = true;
        result.smsServices_ = value;
        return this;
      }
      public Builder SetSmsServices(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasSmsServices = true;
        result.smsServices_ = builderForValue.Build();
        return this;
      }
      public Builder MergeSmsServices(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasSmsServices &&
            result.smsServices_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.smsServices_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.smsServices_).MergeFrom(value).BuildPartial();
        } else {
          result.smsServices_ = value;
        }
        result.hasSmsServices = true;
        return this;
      }
      public Builder ClearSmsServices() {
        result.hasSmsServices = false;
        result.smsServices_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasNoInternationalDialling {
       get { return result.HasNoInternationalDialling; }
      }
      public global::PhoneNumbers.PhoneNumberDesc NoInternationalDialling {
        get { return result.NoInternationalDialling; }
        set { SetNoInternationalDialling(value); }
      }
      public Builder SetNoInternationalDialling(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasNoInternationalDialling = true;
        result.noInternationalDialling_ = value;
        return this;
      }
      public Builder SetNoInternationalDialling(global::PhoneNumbers.PhoneNumberDesc.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.hasNoInternationalDialling = true;
        result.noInternationalDialling_ = builderForValue.Build();
        return this;
      }
      public Builder MergeNoInternationalDialling(global::PhoneNumbers.PhoneNumberDesc value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        if (result.HasNoInternationalDialling &&
            result.noInternationalDialling_ != global::PhoneNumbers.PhoneNumberDesc.DefaultInstance) {
            result.noInternationalDialling_ = global::PhoneNumbers.PhoneNumberDesc.CreateBuilder(result.noInternationalDialling_).MergeFrom(value).BuildPartial();
        } else {
          result.noInternationalDialling_ = value;
        }
        result.hasNoInternationalDialling = true;
        return this;
      }
      public Builder ClearNoInternationalDialling() {
        result.hasNoInternationalDialling = false;
        result.noInternationalDialling_ = global::PhoneNumbers.PhoneNumberDesc.DefaultInstance;
        return this;
      }
      
      public bool HasId {
        get { return result.HasId; }
      }
      public string Id {
        get { return result.Id; }
        set { SetId(value); }
      }
      public Builder SetId(string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder ClearId() {
        result.hasId = false;
        result.id_ = "";
        return this;
      }
      
      public bool HasCountryCode {
        get { return result.HasCountryCode; }
      }
      public int CountryCode {
        get { return result.CountryCode; }
        set { SetCountryCode(value); }
      }
      public Builder SetCountryCode(int value) {
        result.hasCountryCode = true;
        result.countryCode_ = value;
        return this;
      }
      public Builder ClearCountryCode() {
        result.hasCountryCode = false;
        result.countryCode_ = 0;
        return this;
      }
      
      public bool HasInternationalPrefix {
        get { return result.HasInternationalPrefix; }
      }
      public string InternationalPrefix {
        get { return result.InternationalPrefix; }
        set { SetInternationalPrefix(value); }
      }
      public Builder SetInternationalPrefix(string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasInternationalPrefix = true;
        result.internationalPrefix_ = value;
        return this;
      }
      public Builder ClearInternationalPrefix() {
        result.hasInternationalPrefix = false;
        result.internationalPrefix_ = "";
        return this;
      }
      
      public bool HasPreferredInternationalPrefix {
        get { return result.HasPreferredInternationalPrefix; }
      }
      public string PreferredInternationalPrefix {
        get { return result.PreferredInternationalPrefix; }
        set { SetPreferredInternationalPrefix(value); }
      }
      public Builder SetPreferredInternationalPrefix(string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasPreferredInternationalPrefix = true;
        result.preferredInternationalPrefix_ = value;
        return this;
      }
      public Builder ClearPreferredInternationalPrefix() {
        result.hasPreferredInternationalPrefix = false;
        result.preferredInternationalPrefix_ = "";
        return this;
      }
      
      public bool HasNationalPrefix {
        get { return result.HasNationalPrefix; }
      }
      public string NationalPrefix {
        get { return result.NationalPrefix; }
        set { SetNationalPrefix(value); }
      }
      public Builder SetNationalPrefix(string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasNationalPrefix = true;
        result.nationalPrefix_ = value;
        return this;
      }
      public Builder ClearNationalPrefix() {
        result.hasNationalPrefix = false;
        result.nationalPrefix_ = "";
        return this;
      }
      
      public bool HasPreferredExtnPrefix {
        get { return result.HasPreferredExtnPrefix; }
      }
      public string PreferredExtnPrefix {
        get { return result.PreferredExtnPrefix; }
        set { SetPreferredExtnPrefix(value); }
      }
      public Builder SetPreferredExtnPrefix(string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasPreferredExtnPrefix = true;
        result.preferredExtnPrefix_ = value;
        return this;
      }
      public Builder ClearPreferredExtnPrefix() {
        result.hasPreferredExtnPrefix = false;
        result.preferredExtnPrefix_ = "";
        return this;
      }
      
      public bool HasNationalPrefixForParsing {
        get { return result.HasNationalPrefixForParsing; }
      }
      public string NationalPrefixForParsing {
        get { return result.NationalPrefixForParsing; }
        set { SetNationalPrefixForParsing(value); }
      }
      public Builder SetNationalPrefixForParsing(string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasNationalPrefixForParsing = true;
        result.nationalPrefixForParsing_ = value;
        return this;
      }
      public Builder ClearNationalPrefixForParsing() {
        result.hasNationalPrefixForParsing = false;
        result.nationalPrefixForParsing_ = "";
        return this;
      }
      
      public bool HasNationalPrefixTransformRule {
        get { return result.HasNationalPrefixTransformRule; }
      }
      public string NationalPrefixTransformRule {
        get { return result.NationalPrefixTransformRule; }
        set { SetNationalPrefixTransformRule(value); }
      }
      public Builder SetNationalPrefixTransformRule(string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasNationalPrefixTransformRule = true;
        result.nationalPrefixTransformRule_ = value;
        return this;
      }
      public Builder ClearNationalPrefixTransformRule() {
        result.hasNationalPrefixTransformRule = false;
        result.nationalPrefixTransformRule_ = "";
        return this;
      }
      
      public bool HasSameMobileAndFixedLinePattern {
        get { return result.HasSameMobileAndFixedLinePattern; }
      }
      public bool SameMobileAndFixedLinePattern {
        get { return result.SameMobileAndFixedLinePattern; }
        set { SetSameMobileAndFixedLinePattern(value); }
      }
      public Builder SetSameMobileAndFixedLinePattern(bool value) {
        result.hasSameMobileAndFixedLinePattern = true;
        result.sameMobileAndFixedLinePattern_ = value;
        return this;
      }
      public Builder ClearSameMobileAndFixedLinePattern() {
        result.hasSameMobileAndFixedLinePattern = false;
        result.sameMobileAndFixedLinePattern_ = false;
        return this;
      }
      
      public scg::IList<global::PhoneNumbers.NumberFormat> NumberFormatList {
        get { return result.numberFormat_; }
      }
      public int NumberFormatCount {
        get { return result.NumberFormatCount; }
      }
      public global::PhoneNumbers.NumberFormat GetNumberFormat(int index) {
        return result.GetNumberFormat(index);
      }
      public Builder SetNumberFormat(int index, global::PhoneNumbers.NumberFormat value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.numberFormat_[index] = value;
        return this;
      }
      public Builder SetNumberFormat(int index, global::PhoneNumbers.NumberFormat.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.numberFormat_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddNumberFormat(global::PhoneNumbers.NumberFormat value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.numberFormat_.Add(value);
        return this;
      }
      public Builder AddNumberFormat(global::PhoneNumbers.NumberFormat.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.numberFormat_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeNumberFormat(scg::IEnumerable<global::PhoneNumbers.NumberFormat> values) {
         result.numberFormat_.AddRange(values);
        return this;
      }
      public Builder ClearNumberFormat() {
        result.numberFormat_.Clear();
        return this;
      }
      
      public scg::IList<global::PhoneNumbers.NumberFormat> IntlNumberFormatList {
        get { return result.intlNumberFormat_; }
      }
      public int IntlNumberFormatCount {
        get { return result.IntlNumberFormatCount; }
      }
      public global::PhoneNumbers.NumberFormat GetIntlNumberFormat(int index) {
        return result.GetIntlNumberFormat(index);
      }
      public Builder SetIntlNumberFormat(int index, global::PhoneNumbers.NumberFormat value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.intlNumberFormat_[index] = value;
        return this;
      }
      public Builder SetIntlNumberFormat(int index, global::PhoneNumbers.NumberFormat.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.intlNumberFormat_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddIntlNumberFormat(global::PhoneNumbers.NumberFormat value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.intlNumberFormat_.Add(value);
        return this;
      }
      public Builder AddIntlNumberFormat(global::PhoneNumbers.NumberFormat.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.intlNumberFormat_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeIntlNumberFormat(scg::IEnumerable<global::PhoneNumbers.NumberFormat> values) {
         result.intlNumberFormat_.AddRange(values);
        return this;
      }
      public Builder ClearIntlNumberFormat() {
        result.intlNumberFormat_.Clear();
        return this;
      }
      
      public bool HasMainCountryForCode {
        get { return result.HasMainCountryForCode; }
      }
      public bool MainCountryForCode {
        get { return result.MainCountryForCode; }
        set { SetMainCountryForCode(value); }
      }
      public Builder SetMainCountryForCode(bool value) {
        result.hasMainCountryForCode = true;
        result.mainCountryForCode_ = value;
        return this;
      }
      public Builder ClearMainCountryForCode() {
        result.hasMainCountryForCode = false;
        result.mainCountryForCode_ = false;
        return this;
      }
      
      public bool HasLeadingDigits {
        get { return result.HasLeadingDigits; }
      }
      public string LeadingDigits {
        get { return result.LeadingDigits; }
        set { SetLeadingDigits(value); }
      }
      public Builder SetLeadingDigits(string value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.hasLeadingDigits = true;
        result.leadingDigits_ = value;
        return this;
      }
      public Builder ClearLeadingDigits() {
        result.hasLeadingDigits = false;
        result.leadingDigits_ = "";
        return this;
      }
      
      public bool HasLeadingZeroPossible {
        get { return result.HasLeadingZeroPossible; }
      }
      public bool LeadingZeroPossible {
        get { return result.LeadingZeroPossible; }
        set { SetLeadingZeroPossible(value); }
      }
      public Builder SetLeadingZeroPossible(bool value) {
        result.hasLeadingZeroPossible = true;
        result.leadingZeroPossible_ = value;
        return this;
      }
      public Builder ClearLeadingZeroPossible() {
        result.hasLeadingZeroPossible = false;
        result.leadingZeroPossible_ = false;
        return this;
      }
      
      public bool HasMobileNumberPortableRegion {
        get { return result.HasMobileNumberPortableRegion; }
      }
      public bool MobileNumberPortableRegion {
        get { return result.MobileNumberPortableRegion; }
        set { SetMobileNumberPortableRegion(value); }
      }
      public Builder SetMobileNumberPortableRegion(bool value) {
        result.hasMobileNumberPortableRegion = true;
        result.mobileNumberPortableRegion_ = value;
        return this;
      }
      public Builder ClearMobileNumberPortableRegion() {
        result.hasMobileNumberPortableRegion = false;
        result.mobileNumberPortableRegion_ = false;
        return this;
      }
    }
    static PhoneMetadata() {
      object.ReferenceEquals(global::PhoneNumbers.Phonemetadata.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
  public partial class PhoneMetadataCollection {
    private static readonly PhoneMetadataCollection defaultInstance = new Builder().BuildPartial();
    public static PhoneMetadataCollection DefaultInstance {
      get { return defaultInstance; }
    }
    
    public PhoneMetadataCollection DefaultInstanceForType {
      get { return defaultInstance; }
    }
    
    protected PhoneMetadataCollection ThisMessage {
      get { return this; }
    }
    
    public const int MetadataFieldNumber = 1;
    private scg::List<global::PhoneNumbers.PhoneMetadata> metadata_ = new scg::List<global::PhoneNumbers.PhoneMetadata>();
    public scg::IList<global::PhoneNumbers.PhoneMetadata> MetadataList {
      get { return metadata_; }
    }
    public int MetadataCount {
      get { return metadata_.Count; }
    }
    public global::PhoneNumbers.PhoneMetadata GetMetadata(int index) {
      return metadata_[index];
    }
    
    public bool IsInitialized {
      get {
        foreach (global::PhoneNumbers.PhoneMetadata element in MetadataList) {
          if (!element.IsInitialized) return false;
        }
        return true;
      }
    }
    
    
    
    
    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      foreach(global::PhoneNumbers.PhoneMetadata i in metadata_)
        hash ^= i.GetHashCode();
      return hash;
    }
    
    public override bool Equals(object obj) {
      PhoneMetadataCollection other = obj as PhoneMetadataCollection;
      if (other == null) return false;
      if(metadata_.Count != other.metadata_.Count) return false;
      for(int ix=0; ix < metadata_.Count; ix++)
        if(!metadata_[ix].Equals(other.metadata_[ix])) return false;
      return true;
    }
    
    #endregion
    
    public static Builder CreateBuilder() { return new Builder(); }
    public Builder ToBuilder() { return CreateBuilder(this); }
    public Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(PhoneMetadataCollection prototype) {
      return (Builder) new Builder().MergeFrom(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public partial class Builder {
      protected Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {}
      
      PhoneMetadataCollection result = new PhoneMetadataCollection();
      
      protected PhoneMetadataCollection MessageBeingBuilt {
        get { return result; }
      }
      
      public Builder Clear() {
        result = new PhoneMetadataCollection();
        return this;
      }
      
      public Builder Clone() {
        return new Builder().MergeFrom(result);
      }
      
      public PhoneMetadataCollection DefaultInstanceForType {
        get { return global::PhoneNumbers.PhoneMetadataCollection.DefaultInstance; }
      }
      
      public PhoneMetadataCollection Build() { return BuildPartial(); }
      
      public PhoneMetadataCollection BuildPartial() {
        if (result == null) {
          throw new global::System.InvalidOperationException("build() has already been called on this Builder");
        }

        PhoneMetadataCollection returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      public Builder MergeFrom(PhoneMetadataCollection other) {
        if (other == global::PhoneNumbers.PhoneMetadataCollection.DefaultInstance) return this;
        if (other.metadata_.Count != 0) {
           result.metadata_.AddRange(other.metadata_);
        }
        return this;
      }
      
      
      
      
      public scg::IList<global::PhoneNumbers.PhoneMetadata> MetadataList {
        get { return result.metadata_; }
      }
      public int MetadataCount {
        get { return result.MetadataCount; }
      }
      public global::PhoneNumbers.PhoneMetadata GetMetadata(int index) {
        return result.GetMetadata(index);
      }
      public Builder SetMetadata(int index, global::PhoneNumbers.PhoneMetadata value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.metadata_[index] = value;
        return this;
      }
      public Builder SetMetadata(int index, global::PhoneNumbers.PhoneMetadata.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.metadata_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddMetadata(global::PhoneNumbers.PhoneMetadata value) {
        if(value == null) throw new global::System.ArgumentNullException("value");
        result.metadata_.Add(value);
        return this;
      }
      public Builder AddMetadata(global::PhoneNumbers.PhoneMetadata.Builder builderForValue) {
        if(builderForValue == null) throw new global::System.ArgumentNullException("builderForValue");
        result.metadata_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeMetadata(scg::IEnumerable<global::PhoneNumbers.PhoneMetadata> values) {
         result.metadata_.AddRange(values);
        return this;
      }
      public Builder ClearMetadata() {
        result.metadata_.Clear();
        return this;
      }
    }
    static PhoneMetadataCollection() {
      object.ReferenceEquals(global::PhoneNumbers.Phonemetadata.Descriptor, null);
    }
  }
  
  #endregion
  
}
