// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

//#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace PhoneNumbers
{

    public partial class PhoneNumber
    {
        public int? CountryCode { get; set; }

        public ulong? NationalNumber { get; set; }

        public string Extension
        {
            get { return __pbn__Extension ?? ""; }
            set { __pbn__Extension = value; }
        }

        public bool ShouldSerializeExtension() => __pbn__Extension != null;
        public void ResetExtension() => __pbn__Extension = null;
        private string __pbn__Extension;

        public bool ItalianLeadingZero
        {
            get { return __pbn__ItalianLeadingZero.GetValueOrDefault(); }
            set { __pbn__ItalianLeadingZero = value; }
        }

        public bool ShouldSerializeItalianLeadingZero() => __pbn__ItalianLeadingZero != null;
        public void ResetItalianLeadingZero() => __pbn__ItalianLeadingZero = null;
        private bool? __pbn__ItalianLeadingZero;

        public int NumberOfLeadingZeros
        {
            get { return __pbn__NumberOfLeadingZeros ?? 1; }
            set { __pbn__NumberOfLeadingZeros = value; }
        }

        public bool ShouldSerializeNumberOfLeadingZeros() => __pbn__NumberOfLeadingZeros != null;
        public void ResetNumberOfLeadingZeros() => __pbn__NumberOfLeadingZeros = null;
        private int? __pbn__NumberOfLeadingZeros;

        public string RawInput
        {
            get { return __pbn__RawInput ?? ""; }
            set { __pbn__RawInput = value; }
        }

        public bool ShouldSerializeRawInput() => __pbn__RawInput != null;
        public void ResetRawInput() => __pbn__RawInput = null;
        private string __pbn__RawInput;

        public Types.CountryCodeSource? CountryCodeSource
        {
            get { return __pbn__country_code_source; }
            set { __pbn__country_code_source = value; }
        }

        public bool ShouldSerializecountry_code_source() => __pbn__country_code_source != null;
        public void Resetcountry_code_source() => __pbn__country_code_source = null;
        private Types.CountryCodeSource? __pbn__country_code_source;

        public string PreferredDomesticCarrierCode
        {
            get { return __pbn__PreferredDomesticCarrierCode ?? ""; }
            set { __pbn__PreferredDomesticCarrierCode = value; }
        }

        public bool ShouldSerializePreferredDomesticCarrierCode() => __pbn__PreferredDomesticCarrierCode != null;
        public void ResetPreferredDomesticCarrierCode() => __pbn__PreferredDomesticCarrierCode = null;
        private string __pbn__PreferredDomesticCarrierCode;

        public class Types
        {
            public enum CountryCodeSource
            {
                Unspecified = 0,
                FromNumberWithPlusSign = 1,
                FromNumberWithIdd = 5,
                FromNumberWithoutPlusSign = 10,
                FromDefaultCountry = 20,
            }
        }

        internal PhoneNumber MergeFrom(PhoneNumber number)
        {
            CountryCode = number.CountryCode;
            Extension = number.Extension;
            CountryCodeSource = number.CountryCodeSource;
            ItalianLeadingZero = number.ItalianLeadingZero;
            NationalNumber = number.NationalNumber;
            NumberOfLeadingZeros = number.NumberOfLeadingZeros;
            PreferredDomesticCarrierCode = number.PreferredDomesticCarrierCode;
            RawInput = number.RawInput;
            return this;

        }
    }
}

//#pragma warning restore CS1591, CS0612, CS3021, IDE1006
