# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build_and_run_unit_tests_linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_run_unit_tests_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: Add zip files required for running tests
        run: |
          (cd resources/geocoding; zip -r ../../resources/geocoding.zip *)
          (cd resources/test/geocoding; zip -r ../../../resources/test/testgeocoding.zip *)
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./csharp
      - name: Build solution
        run: dotnet build --no-restore
        working-directory: ./csharp
      - name: Test PhoneNumbers.Test project
        run: dotnet test --no-build --verbosity normal
        working-directory: ./csharp/PhoneNumbers.Test
