name: build_and_run_unit_tests_linux

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_run_unit_tests_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Add zip files required for running tests
        run: |
          (cd resources/geocoding; zip -r ../../resources/geocoding.zip *)
          (cd resources/test/geocoding; zip -r ../../../resources/test/testgeocoding.zip *)
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./csharp
      - name: Build solution
        run: dotnet build --no-restore
        working-directory: ./csharp
      - name: Test solution targeting dotnet7.0 only
        run: dotnet test --no-build --verbosity normal -p:TargetFrameworks=net7.0
        working-directory: ./csharp
