name: build_and_run_demo_tests

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'csharp/PhoneNumbers.Demo/**'
      - 'csharp/PhoneNumbers.Demo.Tests/**'
      - 'csharp/PhoneNumbers/**'
      - 'csharp/PhoneNumbers.Extensions/**'
      - 'resources/**'
      - '.github/workflows/build_and_run_demo_tests.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build_and_run_demo_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - name: Setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5
        with:
          dotnet-version: 10.x
      - name: Restore dependencies
        run: dotnet restore PhoneNumbers.Demo.Tests/PhoneNumbers.Demo.Tests.csproj
        working-directory: ./csharp
      - name: Build
        run: dotnet build PhoneNumbers.Demo.Tests/PhoneNumbers.Demo.Tests.csproj --no-restore
        working-directory: ./csharp
      - name: Test demo project
        run: dotnet test PhoneNumbers.Demo.Tests/PhoneNumbers.Demo.Tests.csproj --no-build --verbosity normal
        working-directory: ./csharp
