name: "run_all_tests_and_upload_code_coverage"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_all_tests_and_upload_code_coverage:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.x
      - name: Run tests
        run: dotnet test csharp/PhoneNumbers.sln --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: twcclegg/libphonenumber-csharp
